import 'dotenv/config'
import { db } from '@/db'
import { siteTemplate } from '@/db/schema'

async function seedTemplates() {
  console.log('🌱 Seeding templates...')

  try {
    await db.insert(siteTemplate).values({
      id: 'aurora',
      name: 'Aurora',
      description: 'Design premium para empresas de tecnologia e SaaS. Cantos arredondados, fundo creme quente, glassmorphism, botoes pill e tipografia sofisticada.',
      thumbnailUrl: null,
      previewUrl: '/preview-grovia',
      bestFor: [
        'saas', 'tech', 'startup', 'fintech', 'consultoria', 'agencia',
        'b2b', 'software', 'plataforma', 'app', 'tecnologia', 'digital',
        'marketing-digital', 'automacao', 'inteligencia-artificial', 'ia',
        'desenvolvimento', 'sistemas', 'ti', 'informatica',
      ],
      forceStyle: 'elegant',
      forceRadius: 'lg',
      recommendedHeadingFont: 'inter',
      recommendedBodyFont: 'inter',
      defaultSections: [
        { blockType: 'header', variant: 1, name: 'Header Pill', description: 'Nav flutuante pill-shaped' },
        { blockType: 'hero', variant: 1, name: 'Hero Dashboard', description: 'Split com imagem/mockup' },
        { blockType: 'services', variant: 1, name: 'Process Steps', description: 'Steps numerados com imagem' },
        { blockType: 'services', variant: 2, name: 'Feature Tabs', description: 'Tabs com preview de feature' },
        { blockType: 'stats', variant: 1, name: 'Integration Grid', description: 'Grid de integracoes com steps numerados' },
        { blockType: 'pricing', variant: 1, name: 'Glassmorphism', description: 'Cards com glassmorphism escuro' },
        { blockType: 'testimonials', variant: 1, name: 'Case Studies', description: 'Cases + depoimentos' },
        { blockType: 'faq', variant: 1, name: 'Split Clean', description: 'FAQ split com sticky title' },
        { blockType: 'footer', variant: 1, name: 'Newsletter Grid', description: 'Footer com newsletter e 4 colunas' },
      ],
      availableVariants: {
        header: [1],
        hero: [1],
        services: [1, 2],
        stats: [1],
        pricing: [1],
        testimonials: [1],
        faq: [1],
        footer: [1],
        about: [1],
        contact: [1],
        cta: [1],
        'whatsapp-float': [1],
      },
      sortOrder: 1,
      isActive: true,
    }).onConflictDoUpdate({
      target: siteTemplate.id,
      set: {
        name: 'Aurora',
        description: 'Design premium para empresas de tecnologia e SaaS. Cantos arredondados, fundo creme quente, glassmorphism, botoes pill e tipografia sofisticada.',
        bestFor: [
          'saas', 'tech', 'startup', 'fintech', 'consultoria', 'agencia',
          'b2b', 'software', 'plataforma', 'app', 'tecnologia', 'digital',
          'marketing-digital', 'automacao', 'inteligencia-artificial', 'ia',
          'desenvolvimento', 'sistemas', 'ti', 'informatica',
        ],
        defaultSections: [
          { blockType: 'header', variant: 1, name: 'Header Pill', description: 'Nav flutuante pill-shaped' },
          { blockType: 'hero', variant: 1, name: 'Hero Dashboard', description: 'Split com imagem/mockup' },
          { blockType: 'services', variant: 1, name: 'Process Steps', description: 'Steps numerados com imagem' },
          { blockType: 'services', variant: 2, name: 'Feature Tabs', description: 'Tabs com preview de feature' },
          { blockType: 'stats', variant: 1, name: 'Integration Grid', description: 'Grid de integracoes com steps numerados' },
          { blockType: 'pricing', variant: 1, name: 'Glassmorphism', description: 'Cards com glassmorphism escuro' },
          { blockType: 'testimonials', variant: 1, name: 'Case Studies', description: 'Cases + depoimentos' },
          { blockType: 'faq', variant: 1, name: 'Split Clean', description: 'FAQ split com sticky title' },
          { blockType: 'footer', variant: 1, name: 'Newsletter Grid', description: 'Footer com newsletter e 4 colunas' },
        ],
        updatedAt: new Date(),
      },
    })

    console.log('✅ Template "Aurora" criado/atualizado com sucesso!')

    // ── Torque ──
    await db.insert(siteTemplate).values({
      id: 'plumbflow',
      name: 'Torque',
      description: 'Design profissional e robusto para servicos e manutencao. Dark navy com accent laranja, tipografia Satoshi bold, botoes pill com efeito glossy, timeline animada e formularios de lead.',
      thumbnailUrl: null,
      previewUrl: '/preview-plumbflow',
      bestFor: [
        'encanamento', 'encanador', 'plumbing',
        'eletricista', 'electrician',
        'manutencao', 'maintenance',
        'climatizacao', 'hvac', 'ar-condicionado',
        'pintura', 'painting', 'pintor',
        'reformas', 'construction', 'pedreiro',
        'desentupidora', 'limpeza',
        'servicos-domesticos', 'home-services',
        'serralheria', 'vidracaria',
        'dedetizacao', 'pest-control',
        'jardinagem', 'landscaping',
        'mudancas', 'moving',
        'seguranca', 'alarmes',
        'energia-solar', 'solar',
        'mecanica', 'auto-repair', 'mecanico',
        'chaveiro', 'locksmith',
      ],
      forceStyle: 'bold',
      forceRadius: 'full',
      recommendedHeadingFont: 'satoshi',
      recommendedBodyFont: 'satoshi',
      defaultSections: [
        { blockType: 'header', variant: 1, name: 'Header + Top Bar', description: 'Nav escuro com barra de contato, logo, links e CTA pill orange' },
        { blockType: 'hero', variant: 1, name: 'Hero Full Image', description: 'Hero com bg image, glassmorphism badge e barra de reconhecimento' },
        { blockType: 'contact', variant: 1, name: 'Quick Form', description: 'Formulario rapido inline com nome + telefone' },
        { blockType: 'about', variant: 1, name: 'About Tabs', description: 'Secao about com tabs interativas e checklist' },
        { blockType: 'stats', variant: 1, name: 'Counter Animated', description: 'Contadores animados com scroll trigger' },
        { blockType: 'services', variant: 1, name: 'Services Tabs', description: 'Servicos com lista clicavel e card com imagem' },
        { blockType: 'services', variant: 2, name: 'Process Timeline', description: 'Timeline alternada com scroll progress' },
        { blockType: 'services', variant: 3, name: 'Why Choose Us', description: 'Features com icones e imagem lateral' },
        { blockType: 'testimonials', variant: 1, name: 'Testimonials Dark', description: 'Cards brancos sobre fundo navy escuro' },
        { blockType: 'gallery', variant: 1, name: 'Bento Grid', description: 'Grid bento com card tall + 4 menores' },
        { blockType: 'cta', variant: 1, name: 'CTA + Form', description: 'Banner escuro com formulario de contato overlapping' },
        { blockType: 'footer', variant: 1, name: 'Footer Dark 4-col', description: 'Footer escuro com 4 colunas e social icons' },
      ],
      availableVariants: {
        header: [1],
        hero: [1],
        contact: [1],
        about: [1],
        stats: [1],
        services: [1, 2, 3],
        testimonials: [1],
        gallery: [1],
        cta: [1],
        footer: [1],
      },
      sortOrder: 2,
      isActive: true,
    }).onConflictDoUpdate({
      target: siteTemplate.id,
      set: {
        name: 'Torque',
        description: 'Design profissional e robusto para servicos e manutencao. Dark navy com accent laranja, tipografia Satoshi bold, botoes pill com efeito glossy, timeline animada e formularios de lead.',
        bestFor: [
          'encanamento', 'encanador', 'plumbing',
          'eletricista', 'electrician',
          'manutencao', 'maintenance',
          'climatizacao', 'hvac', 'ar-condicionado',
          'pintura', 'painting', 'pintor',
          'reformas', 'construction', 'pedreiro',
          'desentupidora', 'limpeza',
          'servicos-domesticos', 'home-services',
          'serralheria', 'vidracaria',
          'dedetizacao', 'pest-control',
          'jardinagem', 'landscaping',
          'mudancas', 'moving',
          'seguranca', 'alarmes',
          'energia-solar', 'solar',
          'mecanica', 'auto-repair', 'mecanico',
          'chaveiro', 'locksmith',
        ],
        defaultSections: [
          { blockType: 'header', variant: 1, name: 'Header + Top Bar', description: 'Nav escuro com barra de contato, logo, links e CTA pill orange' },
          { blockType: 'hero', variant: 1, name: 'Hero Full Image', description: 'Hero com bg image, glassmorphism badge e barra de reconhecimento' },
          { blockType: 'contact', variant: 1, name: 'Quick Form', description: 'Formulario rapido inline com nome + telefone' },
          { blockType: 'about', variant: 1, name: 'About Tabs', description: 'Secao about com tabs interativas e checklist' },
          { blockType: 'stats', variant: 1, name: 'Counter Animated', description: 'Contadores animados com scroll trigger' },
          { blockType: 'services', variant: 1, name: 'Services Tabs', description: 'Servicos com lista clicavel e card com imagem' },
          { blockType: 'services', variant: 2, name: 'Process Timeline', description: 'Timeline alternada com scroll progress' },
          { blockType: 'services', variant: 3, name: 'Why Choose Us', description: 'Features com icones e imagem lateral' },
          { blockType: 'testimonials', variant: 1, name: 'Testimonials Dark', description: 'Cards brancos sobre fundo navy escuro' },
          { blockType: 'gallery', variant: 1, name: 'Bento Grid', description: 'Grid bento com card tall + 4 menores' },
          { blockType: 'cta', variant: 1, name: 'CTA + Form', description: 'Banner escuro com formulario de contato overlapping' },
          { blockType: 'footer', variant: 1, name: 'Footer Dark 4-col', description: 'Footer escuro com 4 colunas e social icons' },
        ],
        availableVariants: {
          header: [1],
          hero: [1],
          contact: [1],
          about: [1],
          stats: [1],
          services: [1, 2, 3],
          testimonials: [1],
          gallery: [1],
          cta: [1],
          footer: [1],
        },
        updatedAt: new Date(),
      },
    })

    console.log('✅ Template "Torque" criado/atualizado com sucesso!')

    // ── Roofora (Apex) ──
    await db.insert(siteTemplate).values({
      id: 'roofora',
      name: 'Apex',
      description: 'Design dark premium com accent lime green. Tipografia Urbanist, cards escuros, botoes pill accent vibrante. Ideal para construcao, telhados, solar e reformas.',
      thumbnailUrl: null,
      previewUrl: '/preview-roofora',
      bestFor: [
        'telhado', 'telhados', 'roofing',
        'solar', 'energia-solar', 'painel-solar',
        'construcao', 'construtora', 'construction',
        'impermeabilizacao', 'waterproofing',
        'reforma', 'reformas', 'remodeling',
        'arquitetura', 'architecture',
        'engenharia', 'engineering',
        'terraplanagem', 'excavation',
        'estrutura-metalica', 'steel',
        'gesso', 'drywall',
        'pisos', 'flooring',
        'fachada', 'facade',
        'piscina', 'pool',
      ],
      forceStyle: 'bold',
      forceRadius: 'full',
      recommendedHeadingFont: 'urbanist',
      recommendedBodyFont: 'urbanist',
      defaultSections: [
        { blockType: 'header', variant: 1, name: 'Header Dark', description: 'Nav escuro com logo, links e CTA accent lime' },
        { blockType: 'hero', variant: 1, name: 'Hero Bold', description: 'Hero com titulo grande, 2 CTAs, feature badges abaixo' },
        { blockType: 'about', variant: 1, name: 'About Split', description: 'Imagem + texto + feature list com icones' },
        { blockType: 'services', variant: 1, name: 'Services Grid', description: 'Grid de cards de servicos com icones' },
        { blockType: 'stats', variant: 1, name: 'Stats Counter', description: 'Contadores animados de metricas' },
        { blockType: 'gallery', variant: 1, name: 'Projects Grid', description: 'Portfolio grid com imagens e labels' },
        { blockType: 'services', variant: 2, name: 'How It Works', description: '3 passos numerados com CTA' },
        { blockType: 'testimonials', variant: 1, name: 'Reviews Dark', description: 'Depoimentos sobre fundo escuro' },
        { blockType: 'faq', variant: 1, name: 'FAQ Accordion', description: 'Perguntas e respostas com accordion' },
        { blockType: 'cta', variant: 1, name: 'Newsletter CTA', description: 'CTA com newsletter subscribe' },
        { blockType: 'footer', variant: 1, name: 'Footer Dark', description: 'Footer escuro com 4 colunas e social' },
      ],
      availableVariants: {
        header: [1],
        hero: [1],
        about: [1],
        services: [1, 2],
        stats: [1],
        gallery: [1],
        testimonials: [1],
        faq: [1],
        cta: [1],
        footer: [1],
      },
      sortOrder: 3,
      isActive: true,
    }).onConflictDoUpdate({
      target: siteTemplate.id,
      set: {
        name: 'Apex',
        description: 'Design dark premium com accent lime green. Tipografia Urbanist, cards escuros, botoes pill accent vibrante. Ideal para construcao, telhados, solar e reformas.',
        bestFor: [
          'telhado', 'telhados', 'roofing',
          'solar', 'energia-solar', 'painel-solar',
          'construcao', 'construtora', 'construction',
          'impermeabilizacao', 'waterproofing',
          'reforma', 'reformas', 'remodeling',
          'arquitetura', 'architecture',
          'engenharia', 'engineering',
          'terraplanagem', 'excavation',
          'estrutura-metalica', 'steel',
          'gesso', 'drywall',
          'pisos', 'flooring',
          'fachada', 'facade',
          'piscina', 'pool',
        ],
        defaultSections: [
          { blockType: 'header', variant: 1, name: 'Header Dark', description: 'Nav escuro com logo, links e CTA accent lime' },
          { blockType: 'hero', variant: 1, name: 'Hero Bold', description: 'Hero com titulo grande, 2 CTAs, feature badges abaixo' },
          { blockType: 'about', variant: 1, name: 'About Split', description: 'Imagem + texto + feature list com icones' },
          { blockType: 'services', variant: 1, name: 'Services Grid', description: 'Grid de cards de servicos com icones' },
          { blockType: 'stats', variant: 1, name: 'Stats Counter', description: 'Contadores animados de metricas' },
          { blockType: 'gallery', variant: 1, name: 'Projects Grid', description: 'Portfolio grid com imagens e labels' },
          { blockType: 'services', variant: 2, name: 'How It Works', description: '3 passos numerados com CTA' },
          { blockType: 'testimonials', variant: 1, name: 'Reviews Dark', description: 'Depoimentos sobre fundo escuro' },
          { blockType: 'faq', variant: 1, name: 'FAQ Accordion', description: 'Perguntas e respostas com accordion' },
          { blockType: 'cta', variant: 1, name: 'Newsletter CTA', description: 'CTA com newsletter subscribe' },
          { blockType: 'footer', variant: 1, name: 'Footer Dark', description: 'Footer escuro com 4 colunas e social' },
        ],
        availableVariants: {
          header: [1],
          hero: [1],
          about: [1],
          services: [1, 2],
          stats: [1],
          gallery: [1],
          testimonials: [1],
          faq: [1],
          cta: [1],
          footer: [1],
        },
        updatedAt: new Date(),
      },
    })

    console.log('✅ Template "Apex (Roofora)" criado/atualizado com sucesso!')

    // ── Verve Dent ──
    await db.insert(siteTemplate).values({
      id: 'vervedent',
      name: 'Verve',
      description: 'Design clean healthcare com teal/cyan accent. Inter Display font, cards arredondados, glassmorphism nav. Ideal para clinicas, dentistas e saude.',
      thumbnailUrl: null,
      previewUrl: '/preview-vervedent',
      bestFor: [
        'dentista', 'odontologia', 'dental',
        'clinica', 'clinica-medica', 'clinic',
        'saude', 'healthcare', 'health',
        'estetica', 'aesthetics',
        'dermatologia', 'fisioterapia',
        'psicologia', 'nutricionista',
        'oftalmologia', 'pediatria',
        'ortopedia', 'cardiologia',
        'laboratorio', 'farmacia',
        'veterinaria', 'hospital',
        'bem-estar', 'wellness', 'spa',
      ],
      forceStyle: 'elegant',
      forceRadius: 'lg',
      recommendedHeadingFont: 'inter',
      recommendedBodyFont: 'inter',
      defaultSections: [
        { blockType: 'header', variant: 1, name: 'Header Glass', description: 'Nav glassmorphism com blur, logo, links e CTA pill teal' },
        { blockType: 'hero', variant: 1, name: 'Hero Split', description: 'Hero com titulo, subtitulo, CTA, imagem arredondada e stats' },
        { blockType: 'about', variant: 1, name: 'About Clinic', description: 'Imagem + texto descritivo + endereco' },
        { blockType: 'services', variant: 1, name: 'Team Grid', description: 'Grid de membros da equipe com hover effect' },
        { blockType: 'services', variant: 2, name: 'Services Grid', description: 'Grid de cards de servicos com icones' },
        { blockType: 'contact', variant: 1, name: 'Appointment Form', description: 'Formulario de agendamento + horarios' },
        { blockType: 'testimonials', variant: 1, name: 'Testimonials Carousel', description: 'Carousel de depoimentos com foto e quote' },
        { blockType: 'cta', variant: 1, name: 'Newsletter CTA', description: 'Subscribe newsletter com input + botao' },
        { blockType: 'footer', variant: 1, name: 'Footer Clean', description: 'Logo + social + links + copyright' },
      ],
      availableVariants: {
        header: [1],
        hero: [1],
        about: [1],
        services: [1, 2],
        contact: [1],
        testimonials: [1],
        cta: [1],
        footer: [1],
      },
      sortOrder: 4,
      isActive: true,
    }).onConflictDoUpdate({
      target: siteTemplate.id,
      set: {
        name: 'Verve',
        description: 'Design clean healthcare com teal/cyan accent. Inter Display font, cards arredondados, glassmorphism nav. Ideal para clinicas, dentistas e saude.',
        bestFor: [
          'dentista', 'odontologia', 'dental',
          'clinica', 'clinica-medica', 'clinic',
          'saude', 'healthcare', 'health',
          'estetica', 'aesthetics',
          'dermatologia', 'fisioterapia',
          'psicologia', 'nutricionista',
          'oftalmologia', 'pediatria',
          'ortopedia', 'cardiologia',
          'laboratorio', 'farmacia',
          'veterinaria', 'hospital',
          'bem-estar', 'wellness', 'spa',
        ],
        defaultSections: [
          { blockType: 'header', variant: 1, name: 'Header Glass', description: 'Nav glassmorphism com blur, logo, links e CTA pill teal' },
          { blockType: 'hero', variant: 1, name: 'Hero Split', description: 'Hero com titulo, subtitulo, CTA, imagem arredondada e stats' },
          { blockType: 'about', variant: 1, name: 'About Clinic', description: 'Imagem + texto descritivo + endereco' },
          { blockType: 'services', variant: 1, name: 'Team Grid', description: 'Grid de membros da equipe com hover effect' },
          { blockType: 'services', variant: 2, name: 'Services Grid', description: 'Grid de cards de servicos com icones' },
          { blockType: 'contact', variant: 1, name: 'Appointment Form', description: 'Formulario de agendamento + horarios' },
          { blockType: 'testimonials', variant: 1, name: 'Testimonials Carousel', description: 'Carousel de depoimentos com foto e quote' },
          { blockType: 'cta', variant: 1, name: 'Newsletter CTA', description: 'Subscribe newsletter com input + botao' },
          { blockType: 'footer', variant: 1, name: 'Footer Clean', description: 'Logo + social + links + copyright' },
        ],
        availableVariants: {
          header: [1],
          hero: [1],
          about: [1],
          services: [1, 2],
          contact: [1],
          testimonials: [1],
          cta: [1],
          footer: [1],
        },
        updatedAt: new Date(),
      },
    })

    console.log('✅ Template "Verve (Verve Dent)" criado/atualizado com sucesso!')

    // ── Bellezza (Bloom) ──
    await db.insert(siteTemplate).values({
      id: 'bellezza',
      name: 'Bloom',
      description: 'Design elegante para cosmeticos e beleza. Playfair Display + Poppins, rose gold accent, cards arredondados, catalogo de produtos.',
      thumbnailUrl: null,
      previewUrl: '/preview-bellezza',
      bestFor: [
        'cosmeticos', 'cosmetics', 'beauty', 'beleza',
        'skincare', 'perfumaria', 'perfume',
        'maquiagem', 'makeup', 'cabelo', 'hair',
        'cabeleireiro', 'salao-de-beleza', 'spa',
        'wellness', 'estetica', 'joias', 'jewelry',
        'moda', 'fashion', 'acessorios', 'loja',
        'store', 'e-commerce', 'ecommerce', 'boutique',
        'flores', 'floricultura', 'velas', 'aromaterapia',
      ],
      forceStyle: 'elegant',
      forceRadius: 'lg',
      recommendedHeadingFont: 'playfair-display',
      recommendedBodyFont: 'poppins',
      defaultSections: [
        { blockType: 'header', variant: 1, name: 'Header Elegant', description: 'Nav com logo, links, icones cart/search' },
        { blockType: 'hero', variant: 1, name: 'Hero Beauty', description: 'Hero com titulo grande, subtitulo, CTA e imagem arredondada' },
        { blockType: 'about', variant: 1, name: 'Product Showcase', description: 'Banner de destaque com imagem + stats' },
        { blockType: 'catalog', variant: 1, name: 'Categories', description: 'Cards de categorias com imagem arredondada' },
        { blockType: 'featured-products', variant: 1, name: 'Bestsellers', description: 'Grid de produtos destaque com preco' },
        { blockType: 'services', variant: 1, name: 'Benefits', description: 'Grid de beneficios com icones' },
        { blockType: 'featured-products', variant: 2, name: 'Product List', description: 'Grid de todos os produtos' },
        { blockType: 'gallery', variant: 1, name: 'Blog Articles', description: 'Cards de artigos do blog' },
        { blockType: 'cta', variant: 1, name: 'Instagram Feed', description: 'Grid de fotos Instagram + CTA follow' },
        { blockType: 'footer', variant: 1, name: 'Footer Elegant', description: 'Newsletter + links + social + copyright' },
      ],
      availableVariants: {
        header: [1],
        hero: [1],
        about: [1],
        catalog: [1],
        'featured-products': [1, 2],
        services: [1],
        gallery: [1],
        cta: [1],
        footer: [1],
      },
      sortOrder: 5,
      isActive: true,
    }).onConflictDoUpdate({
      target: siteTemplate.id,
      set: {
        name: 'Bloom',
        description: 'Design elegante para cosmeticos e beleza. Playfair Display + Poppins, rose gold accent, cards arredondados, catalogo de produtos.',
        bestFor: [
          'cosmeticos', 'cosmetics', 'beauty', 'beleza',
          'skincare', 'perfumaria', 'perfume',
          'maquiagem', 'makeup', 'cabelo', 'hair',
          'cabeleireiro', 'salao-de-beleza', 'spa',
          'wellness', 'estetica', 'joias', 'jewelry',
          'moda', 'fashion', 'acessorios', 'loja',
          'store', 'e-commerce', 'ecommerce', 'boutique',
          'flores', 'floricultura', 'velas', 'aromaterapia',
        ],
        defaultSections: [
          { blockType: 'header', variant: 1, name: 'Header Elegant', description: 'Nav com logo, links, icones cart/search' },
          { blockType: 'hero', variant: 1, name: 'Hero Beauty', description: 'Hero com titulo grande, subtitulo, CTA e imagem arredondada' },
          { blockType: 'about', variant: 1, name: 'Product Showcase', description: 'Banner de destaque com imagem + stats' },
          { blockType: 'catalog', variant: 1, name: 'Categories', description: 'Cards de categorias com imagem arredondada' },
          { blockType: 'featured-products', variant: 1, name: 'Bestsellers', description: 'Grid de produtos destaque com preco' },
          { blockType: 'services', variant: 1, name: 'Benefits', description: 'Grid de beneficios com icones' },
          { blockType: 'featured-products', variant: 2, name: 'Product List', description: 'Grid de todos os produtos' },
          { blockType: 'gallery', variant: 1, name: 'Blog Articles', description: 'Cards de artigos do blog' },
          { blockType: 'cta', variant: 1, name: 'Instagram Feed', description: 'Grid de fotos Instagram + CTA follow' },
          { blockType: 'footer', variant: 1, name: 'Footer Elegant', description: 'Newsletter + links + social + copyright' },
        ],
        availableVariants: {
          header: [1],
          hero: [1],
          about: [1],
          catalog: [1],
          'featured-products': [1, 2],
          services: [1],
          gallery: [1],
          cta: [1],
          footer: [1],
        },
        updatedAt: new Date(),
      },
    })

    console.log('✅ Template "Bloom (Bellezza)" criado/atualizado com sucesso!')

    // ── Folioxa (Folio) ──
    await db.insert(siteTemplate).values({
      id: 'folioxa',
      name: 'Folio',
      description: 'Portfolio criativo com dark/orange accent. Outfit font, cards arredondados, pricing, FAQ accordion. Ideal para freelancers, agencias e criativos.',
      thumbnailUrl: null,
      previewUrl: '/preview-folioxa',
      bestFor: [
        'portfolio', 'freelancer', 'designer',
        'agencia', 'agencia-digital', 'agency',
        'criativo', 'creative',
        'desenvolvedor', 'developer', 'programador',
        'fotografo', 'photographer',
        'videomaker', 'filmmaker',
        'ilustrador',
        'marketing-digital', 'social-media',
        'branding', 'web-design', 'ui-ux',
        'consultoria-digital', 'startup',
      ],
      forceStyle: 'bold',
      forceRadius: 'lg',
      recommendedHeadingFont: 'outfit',
      recommendedBodyFont: 'outfit',
      defaultSections: [
        { blockType: 'header', variant: 1, name: 'Header Dark', description: 'Nav escuro sticky com logo, links e CTA pill orange' },
        { blockType: 'hero', variant: 1, name: 'Hero Profile', description: 'Hero com nome, titulo, bio, foto e tech stack' },
        { blockType: 'gallery', variant: 1, name: 'Projects Grid', description: 'Grid de projetos com imagem, tags e ano' },
        { blockType: 'about', variant: 1, name: 'About Split', description: 'Foto + bio + skills em split layout' },
        { blockType: 'services', variant: 1, name: 'Process Steps', description: '3 passos: Design, Build, Launch' },
        { blockType: 'services', variant: 2, name: 'Services Cards', description: 'Cards de servicos com icones e CTA' },
        { blockType: 'stats', variant: 1, name: 'Awards', description: 'Awards e reconhecimentos com badges' },
        { blockType: 'services', variant: 3, name: 'How It Works', description: '3 passos detalhados com imagens' },
        { blockType: 'pricing', variant: 1, name: 'Pricing Plans', description: '2-3 planos com features e CTA' },
        { blockType: 'testimonials', variant: 1, name: 'Testimonials', description: 'Cards de depoimento com rating stars' },
        { blockType: 'faq', variant: 1, name: 'FAQ Accordion', description: 'Perguntas frequentes com accordion' },
        { blockType: 'cta', variant: 1, name: 'CTA Dark', description: 'Call to action sobre fundo escuro' },
        { blockType: 'footer', variant: 1, name: 'Footer Minimal', description: 'Footer minimalista com creditos' },
      ],
      availableVariants: {
        header: [1],
        hero: [1],
        gallery: [1],
        about: [1],
        services: [1, 2, 3],
        stats: [1],
        pricing: [1],
        testimonials: [1],
        faq: [1],
        cta: [1],
        footer: [1],
      },
      sortOrder: 6,
      isActive: true,
    }).onConflictDoUpdate({
      target: siteTemplate.id,
      set: {
        name: 'Folio',
        description: 'Portfolio criativo com dark/orange accent. Outfit font, cards arredondados, pricing, FAQ accordion. Ideal para freelancers, agencias e criativos.',
        bestFor: [
          'portfolio', 'freelancer', 'designer',
          'agencia', 'agencia-digital', 'agency',
          'criativo', 'creative',
          'desenvolvedor', 'developer', 'programador',
          'fotografo', 'photographer',
          'videomaker', 'filmmaker',
          'ilustrador',
          'marketing-digital', 'social-media',
          'branding', 'web-design', 'ui-ux',
          'consultoria-digital', 'startup',
        ],
        defaultSections: [
          { blockType: 'header', variant: 1, name: 'Header Dark', description: 'Nav escuro sticky com logo, links e CTA pill orange' },
          { blockType: 'hero', variant: 1, name: 'Hero Profile', description: 'Hero com nome, titulo, bio, foto e tech stack' },
          { blockType: 'gallery', variant: 1, name: 'Projects Grid', description: 'Grid de projetos com imagem, tags e ano' },
          { blockType: 'about', variant: 1, name: 'About Split', description: 'Foto + bio + skills em split layout' },
          { blockType: 'services', variant: 1, name: 'Process Steps', description: '3 passos: Design, Build, Launch' },
          { blockType: 'services', variant: 2, name: 'Services Cards', description: 'Cards de servicos com icones e CTA' },
          { blockType: 'stats', variant: 1, name: 'Awards', description: 'Awards e reconhecimentos com badges' },
          { blockType: 'services', variant: 3, name: 'How It Works', description: '3 passos detalhados com imagens' },
          { blockType: 'pricing', variant: 1, name: 'Pricing Plans', description: '2-3 planos com features e CTA' },
          { blockType: 'testimonials', variant: 1, name: 'Testimonials', description: 'Cards de depoimento com rating stars' },
          { blockType: 'faq', variant: 1, name: 'FAQ Accordion', description: 'Perguntas frequentes com accordion' },
          { blockType: 'cta', variant: 1, name: 'CTA Dark', description: 'Call to action sobre fundo escuro' },
          { blockType: 'footer', variant: 1, name: 'Footer Minimal', description: 'Footer minimalista com creditos' },
        ],
        availableVariants: {
          header: [1],
          hero: [1],
          gallery: [1],
          about: [1],
          services: [1, 2, 3],
          stats: [1],
          pricing: [1],
          testimonials: [1],
          faq: [1],
          cta: [1],
          footer: [1],
        },
        updatedAt: new Date(),
      },
    })

    console.log('✅ Template "Folio (Folioxa)" criado/atualizado com sucesso!')

    // ── Realestic ──
    await db.insert(siteTemplate).values({
      id: 'realestic',
      name: 'Realestic',
      description: 'Design moderno imobiliário. Cantos arredondados, accent azul vibrante, Satoshi font, cards com imagens grandes, sections limpas com dot-tag.',
      thumbnailUrl: null,
      previewUrl: '/preview-realestic',
      bestFor: [
        'imobiliaria', 'imoveis', 'corretor', 'construtora', 'incorporadora',
        'aluguel', 'venda-imoveis', 'casa', 'apartamento', 'loteamento',
        'condominio', 'empreendimento', 'real-estate', 'property',
        'arquitetura', 'engenharia', 'reforma', 'decoracao', 'interiores',
        'mobiliario', 'moveis', 'hotel', 'pousada', 'airbnb', 'hospedagem',
      ],
      forceStyle: 'elegant',
      forceRadius: 'lg',
      recommendedHeadingFont: 'satoshi',
      recommendedBodyFont: 'satoshi',
      defaultSections: [
        { blockType: 'header', variant: 1, name: 'Flat Nav', description: 'Nav plana com logo + links + CTA pill accent' },
        { blockType: 'hero', variant: 1, name: 'Hero Centered', description: 'Tag pill + H1 centralizado + cover image grande radius 38px' },
        { blockType: 'services', variant: 1, name: 'Vision Cards', description: '2-col: heading left + 3 icon cards horizontais right' },
        { blockType: 'gallery', variant: 1, name: 'Property Grid', description: 'Grid 3x de property cards com imagem, badge, location, details' },
        { blockType: 'services', variant: 2, name: 'Feature Grid', description: 'Grid 3x de features com icon light + titulo + descricao em card bg' },
        { blockType: 'testimonials', variant: 1, name: 'Quote Split', description: '2-col: imagem portrait left + citacao + assinatura right' },
        { blockType: 'faq', variant: 1, name: 'Accordion Split', description: '2-col: accordion left com line indicator + imagem right' },
        { blockType: 'about', variant: 1, name: 'Why Us Overlay', description: 'Imagem full-width com card checklist overlay' },
        { blockType: 'testimonials', variant: 2, name: 'Carousel Cards', description: 'Carousel horizontal com avatar + quote em card accent-light' },
        { blockType: 'stats', variant: 1, name: 'Blog Grid', description: 'Grid 3x de blog cards com imagem + category badge + titulo' },
        { blockType: 'cta', variant: 1, name: 'CTA Accent Card', description: 'Card grande bg accent com titulo + subtitulo + botao white' },
        { blockType: 'footer', variant: 1, name: 'Grid Footer', description: '2-col: heading + social left, 3 link columns right + bottom bar' },
      ],
      availableVariants: {
        header: [1],
        hero: [1],
        services: [1, 2],
        gallery: [1],
        testimonials: [1, 2],
        faq: [1],
        about: [1],
        stats: [1],
        cta: [1],
        footer: [1],
      },
      sortOrder: 7,
      isActive: true,
    }).onConflictDoUpdate({
      target: siteTemplate.id,
      set: {
        name: 'Realestic',
        description: 'Design moderno imobiliário. Cantos arredondados, accent azul vibrante, Satoshi font, cards com imagens grandes, sections limpas com dot-tag.',
        bestFor: [
          'imobiliaria', 'imoveis', 'corretor', 'construtora', 'incorporadora',
          'aluguel', 'venda-imoveis', 'casa', 'apartamento', 'loteamento',
          'condominio', 'empreendimento', 'real-estate', 'property',
          'arquitetura', 'engenharia', 'reforma', 'decoracao', 'interiores',
          'mobiliario', 'moveis', 'hotel', 'pousada', 'airbnb', 'hospedagem',
        ],
        defaultSections: [
          { blockType: 'header', variant: 1, name: 'Flat Nav', description: 'Nav plana com logo + links + CTA pill accent' },
          { blockType: 'hero', variant: 1, name: 'Hero Centered', description: 'Tag pill + H1 centralizado + cover image grande radius 38px' },
          { blockType: 'services', variant: 1, name: 'Vision Cards', description: '2-col: heading left + 3 icon cards horizontais right' },
          { blockType: 'gallery', variant: 1, name: 'Property Grid', description: 'Grid 3x de property cards com imagem, badge, location, details' },
          { blockType: 'services', variant: 2, name: 'Feature Grid', description: 'Grid 3x de features com icon light + titulo + descricao em card bg' },
          { blockType: 'testimonials', variant: 1, name: 'Quote Split', description: '2-col: imagem portrait left + citacao + assinatura right' },
          { blockType: 'faq', variant: 1, name: 'Accordion Split', description: '2-col: accordion left com line indicator + imagem right' },
          { blockType: 'about', variant: 1, name: 'Why Us Overlay', description: 'Imagem full-width com card checklist overlay' },
          { blockType: 'testimonials', variant: 2, name: 'Carousel Cards', description: 'Carousel horizontal com avatar + quote em card accent-light' },
          { blockType: 'stats', variant: 1, name: 'Blog Grid', description: 'Grid 3x de blog cards com imagem + category badge + titulo' },
          { blockType: 'cta', variant: 1, name: 'CTA Accent Card', description: 'Card grande bg accent com titulo + subtitulo + botao white' },
          { blockType: 'footer', variant: 1, name: 'Grid Footer', description: '2-col: heading + social left, 3 link columns right + bottom bar' },
        ],
        availableVariants: {
          header: [1],
          hero: [1],
          services: [1, 2],
          gallery: [1],
          testimonials: [1, 2],
          faq: [1],
          about: [1],
          stats: [1],
          cta: [1],
          footer: [1],
        },
        updatedAt: new Date(),
      },
    })

    console.log('✅ Template "Realestic" criado/atualizado com sucesso!')

    // ── Stratex ──
    await db.insert(siteTemplate).values({
      id: 'stratex',
      name: 'Stratex',
      description: 'Design premium para consultoria e negócios. Serif font, accent teal green, hero escuro, comparison grid, pricing cards, form de contato.',
      thumbnailUrl: null,
      previewUrl: '/preview-stratex',
      bestFor: [
        'consultoria', 'consulting', 'negocio', 'business', 'estrategia',
        'gestao', 'financeiro', 'contabilidade', 'advocacia', 'escritorio',
        'coaching', 'mentoria', 'treinamento', 'rh', 'recrutamento',
        'seguros', 'investimentos', 'assessoria', 'auditoria', 'compliance',
        'b2b', 'saas', 'plataforma', 'agencia', 'marketing',
      ],
      forceStyle: 'elegant',
      forceRadius: 'lg',
      recommendedHeadingFont: 'playfair-display',
      recommendedBodyFont: 'inter',
      defaultSections: [
        { blockType: 'header', variant: 1, name: 'Flat Serif Nav', description: 'Nav com logo green square + serif links + CTA pill com arrow' },
        { blockType: 'hero', variant: 1, name: 'Dark Hero', description: 'Hero escuro bg accent, stars rating, H1 serif, CTAs, hero image' },
        { blockType: 'stats', variant: 1, name: 'Partners Bar', description: 'Logo marquee de parceiros com grayscale' },
        { blockType: 'about', variant: 1, name: 'Comparison Grid', description: '2-col: Other Firms vs Our Firm com checklist' },
        { blockType: 'services', variant: 2, name: 'Service Cards', description: 'Slideshow de cards com imagem bg + gradient overlay' },
        { blockType: 'testimonials', variant: 1, name: 'Dark Carousel', description: 'Stars + carousel de depoimentos escuros' },
        { blockType: 'services', variant: 1, name: 'Feature Grid', description: 'Grid 3x2 de features com icon accent square' },
        { blockType: 'pricing', variant: 1, name: 'Pricing Tiers', description: '2 cards: Standard + Premium' },
        { blockType: 'services', variant: 3, name: 'Numbered Steps', description: '3 steps com imagem + numero + titulo' },
        { blockType: 'stats', variant: 2, name: 'Impact Stats', description: 'Grid com numeros grandes' },
        { blockType: 'gallery', variant: 1, name: 'Team Carousel', description: 'Carousel de membros com foto + nome' },
        { blockType: 'faq', variant: 1, name: 'Clean Accordion', description: 'Accordion simples full-width' },
        { blockType: 'contact', variant: 1, name: 'Dark Form', description: 'Secao escura com form de contato' },
        { blockType: 'footer', variant: 1, name: '4-Col Footer', description: 'Brand + 3 link columns + copyright' },
      ],
      availableVariants: {
        header: [1],
        hero: [1],
        stats: [1, 2],
        about: [1],
        services: [1, 2, 3],
        testimonials: [1],
        pricing: [1],
        gallery: [1],
        faq: [1],
        contact: [1],
        footer: [1],
      },
      sortOrder: 8,
      isActive: true,
    }).onConflictDoUpdate({
      target: siteTemplate.id,
      set: {
        name: 'Stratex',
        description: 'Design premium para consultoria e negócios. Serif font, accent teal green, hero escuro, comparison grid, pricing cards, form de contato.',
        bestFor: [
          'consultoria', 'consulting', 'negocio', 'business', 'estrategia',
          'gestao', 'financeiro', 'contabilidade', 'advocacia', 'escritorio',
          'coaching', 'mentoria', 'treinamento', 'rh', 'recrutamento',
          'seguros', 'investimentos', 'assessoria', 'auditoria', 'compliance',
          'b2b', 'saas', 'plataforma', 'agencia', 'marketing',
        ],
        defaultSections: [
          { blockType: 'header', variant: 1, name: 'Flat Serif Nav', description: 'Nav com logo green square + serif links + CTA pill com arrow' },
          { blockType: 'hero', variant: 1, name: 'Dark Hero', description: 'Hero escuro bg accent, stars rating, H1 serif, CTAs, hero image' },
          { blockType: 'stats', variant: 1, name: 'Partners Bar', description: 'Logo marquee de parceiros com grayscale' },
          { blockType: 'about', variant: 1, name: 'Comparison Grid', description: '2-col: Other Firms vs Our Firm com checklist' },
          { blockType: 'services', variant: 2, name: 'Service Cards', description: 'Slideshow de cards com imagem bg + gradient overlay' },
          { blockType: 'testimonials', variant: 1, name: 'Dark Carousel', description: 'Stars + carousel de depoimentos escuros' },
          { blockType: 'pricing', variant: 1, name: 'Pricing Tiers', description: '2 cards: Standard + Premium' },
          { blockType: 'services', variant: 3, name: 'Numbered Steps', description: '3 steps com imagem + numero + titulo' },
          { blockType: 'stats', variant: 2, name: 'Impact Stats', description: 'Grid com numeros grandes' },
          { blockType: 'gallery', variant: 1, name: 'Team Carousel', description: 'Carousel de membros com foto + nome' },
          { blockType: 'faq', variant: 1, name: 'Clean Accordion', description: 'Accordion simples full-width' },
          { blockType: 'contact', variant: 1, name: 'Dark Form', description: 'Secao escura com form de contato' },
          { blockType: 'footer', variant: 1, name: '4-Col Footer', description: 'Brand + 3 link columns + copyright' },
        ],
        availableVariants: {
          header: [1],
          hero: [1],
          stats: [1, 2],
          about: [1],
          services: [1, 2, 3],
          testimonials: [1],
          pricing: [1],
          gallery: [1],
          faq: [1],
          contact: [1],
          footer: [1],
        },
        updatedAt: new Date(),
      },
    })

    console.log('✅ Template "Stratex" criado/atualizado com sucesso!')

    // ── Cleanly ──
    await db.insert(siteTemplate).values({
      id: 'cleanly',
      name: 'Cleanly',
      description: 'Design vibrante para serviços de limpeza e manutenção. Accent amarelo, Inter font, hero dark, cards de serviço, steps numerados, FAQ accordion.',
      thumbnailUrl: null,
      previewUrl: '/preview-cleanly',
      bestFor: [
        'limpeza', 'cleaning', 'faxina', 'diarista', 'lavanderia',
        'higienizacao', 'dedetizacao', 'manutencao', 'reparos',
        'jardinagem', 'paisagismo', 'piscina', 'ar-condicionado',
        'eletricista', 'encanador', 'pintor', 'mudanca',
        'servicos-domesticos', 'servicos-gerais', 'zeladoria',
      ],
      forceStyle: 'bold',
      forceRadius: 'lg',
      recommendedHeadingFont: 'inter',
      recommendedBodyFont: 'inter',
      defaultSections: [
        { blockType: 'header', variant: 1, name: 'Dark Nav', description: 'Nav escura com top bar + CTA yellow' },
        { blockType: 'hero', variant: 1, name: 'Dark Hero', description: 'Hero escuro com rating + H1 + CTA yellow + imagem' },
        { blockType: 'stats', variant: 1, name: 'Brand Bar', description: 'Logo marquee' },
        { blockType: 'services', variant: 1, name: 'Service Cards', description: 'Grid 3x de cards' },
        { blockType: 'about', variant: 1, name: 'Why Choose Us', description: 'Split imagem + features' },
        { blockType: 'services', variant: 2, name: 'How It Works', description: '3 steps numerados' },
        { blockType: 'stats', variant: 2, name: 'Impact Stats', description: 'Grid de stats' },
        { blockType: 'services', variant: 3, name: 'Benefits', description: 'Accordion de beneficios' },
        { blockType: 'testimonials', variant: 1, name: 'Testimonial Carousel', description: 'Carousel com stars' },
        { blockType: 'faq', variant: 1, name: 'FAQ Accordion', description: 'Accordion' },
        { blockType: 'cta', variant: 1, name: 'CTA Dark', description: 'CTA com bg escuro' },
        { blockType: 'footer', variant: 1, name: 'Dark Footer', description: 'Footer escuro' },
      ],
      availableVariants: {
        header: [1],
        hero: [1],
        stats: [1, 2],
        services: [1, 2, 3],
        about: [1],
        testimonials: [1],
        faq: [1],
        cta: [1],
        footer: [1],
      },
      sortOrder: 9,
      isActive: true,
    }).onConflictDoUpdate({
      target: siteTemplate.id,
      set: {
        name: 'Cleanly',
        description: 'Design vibrante para serviços de limpeza e manutenção. Accent amarelo, Inter font, hero dark, cards de serviço, steps numerados, FAQ accordion.',
        bestFor: [
          'limpeza', 'cleaning', 'faxina', 'diarista', 'lavanderia',
          'higienizacao', 'dedetizacao', 'manutencao', 'reparos',
          'jardinagem', 'paisagismo', 'piscina', 'ar-condicionado',
          'eletricista', 'encanador', 'pintor', 'mudanca',
          'servicos-domesticos', 'servicos-gerais', 'zeladoria',
        ],
        defaultSections: [
          { blockType: 'header', variant: 1, name: 'Dark Nav', description: 'Nav escura com top bar + CTA yellow' },
          { blockType: 'hero', variant: 1, name: 'Dark Hero', description: 'Hero escuro com rating + H1 + CTA yellow + imagem' },
          { blockType: 'stats', variant: 1, name: 'Brand Bar', description: 'Logo marquee' },
          { blockType: 'services', variant: 1, name: 'Service Cards', description: 'Grid 3x de cards' },
          { blockType: 'about', variant: 1, name: 'Why Choose Us', description: 'Split imagem + features' },
          { blockType: 'services', variant: 2, name: 'How It Works', description: '3 steps numerados' },
          { blockType: 'stats', variant: 2, name: 'Impact Stats', description: 'Grid de stats' },
          { blockType: 'services', variant: 3, name: 'Benefits', description: 'Accordion de beneficios' },
          { blockType: 'testimonials', variant: 1, name: 'Testimonial Carousel', description: 'Carousel com stars' },
          { blockType: 'faq', variant: 1, name: 'FAQ Accordion', description: 'Accordion' },
          { blockType: 'cta', variant: 1, name: 'CTA Dark', description: 'CTA com bg escuro' },
          { blockType: 'footer', variant: 1, name: 'Dark Footer', description: 'Footer escuro' },
        ],
        availableVariants: {
          header: [1],
          hero: [1],
          stats: [1, 2],
          services: [1, 2, 3],
          about: [1],
          testimonials: [1],
          faq: [1],
          cta: [1],
          footer: [1],
        },
        updatedAt: new Date(),
      },
    })

    console.log('✅ Template "Cleanly" criado/atualizado com sucesso!')

    // ═══ LARKO ═══
    await db.insert(siteTemplate).values({
      id: 'larko',
      name: 'Larko',
      description: 'Marketing e consultoria com palette verde escuro + lime accent. Geist/Newsreader fonts, cards 6px radius, botoes pill 50px. Ideal para consultorias, agencias de marketing e negocios B2B.',
      thumbnailUrl: null,
      previewUrl: '/preview-larko',
      bestFor: [
        'consultoria', 'consulting', 'consultoria-empresarial',
        'marketing', 'marketing-digital', 'agencia-marketing',
        'agencia', 'agency', 'agencia-digital',
        'negocios', 'business', 'b2b',
        'estrategia', 'strategy',
        'gestao', 'management',
        'financeiro', 'financial', 'contabilidade',
        'juridico', 'law', 'advocacia', 'advogado',
        'rh', 'recursos-humanos', 'recrutamento',
        'coaching', 'mentoria', 'treinamento',
        'tecnologia', 'ti', 'software',
        'logistica', 'supply-chain',
      ],
      forceStyle: 'elegant',
      forceRadius: 'sm',
      recommendedHeadingFont: 'geist',
      recommendedBodyFont: 'geist',
      defaultSections: [
        { blockType: 'header', variant: 1, name: 'Header Larko', description: 'Nav branco com logo texto, links e CTA pill verde' },
        { blockType: 'hero', variant: 1, name: 'Hero Banner', description: 'Hero com headline grande, logos de clientes e stats' },
        { blockType: 'services', variant: 1, name: 'Cards Services', description: '4 cards de servicos com icones lime e numeros' },
        { blockType: 'gallery', variant: 1, name: 'Portfolio Cases', description: '3 cases de portfolio com imagens e descricao' },
        { blockType: 'about', variant: 1, name: 'About Carousel', description: 'Sobre nos com slider e 4 vantagens com icones' },
        { blockType: 'cta', variant: 1, name: 'CTA Green', description: 'CTA escuro com gradiente, headline e slider de depoimentos' },
        { blockType: 'services', variant: 2, name: 'Solutions Grid', description: '3 colunas de solucoes com categorias e outputs' },
        { blockType: 'testimonials', variant: 1, name: 'Testimonials Slider', description: 'Slider de depoimentos com nomes e cargos' },
        { blockType: 'footer', variant: 1, name: 'Footer Dark Green', description: 'Footer verde escuro com form, links, social e copyright' },
      ],
      availableVariants: {
        header: [1],
        hero: [1],
        services: [1, 2],
        gallery: [1],
        about: [1],
        cta: [1],
        testimonials: [1],
        footer: [1],
      },
      sortOrder: 9,
      isActive: true,
    }).onConflictDoUpdate({
      target: siteTemplate.id,
      set: {
        name: 'Larko',
        description: 'Marketing e consultoria com palette verde escuro + lime accent. Geist/Newsreader fonts, cards 6px radius, botoes pill 50px. Ideal para consultorias, agencias de marketing e negocios B2B.',
        bestFor: [
          'consultoria', 'consulting', 'consultoria-empresarial',
          'marketing', 'marketing-digital', 'agencia-marketing',
          'agencia', 'agency', 'agencia-digital',
          'negocios', 'business', 'b2b',
          'estrategia', 'strategy',
          'gestao', 'management',
          'financeiro', 'financial', 'contabilidade',
          'juridico', 'law', 'advocacia', 'advogado',
          'rh', 'recursos-humanos', 'recrutamento',
          'coaching', 'mentoria', 'treinamento',
          'tecnologia', 'ti', 'software',
          'logistica', 'supply-chain',
        ],
        forceStyle: 'elegant',
        forceRadius: 'sm',
        recommendedHeadingFont: 'geist',
        recommendedBodyFont: 'geist',
        defaultSections: [
          { blockType: 'header', variant: 1, name: 'Header Larko', description: 'Nav branco com logo texto, links e CTA pill verde' },
          { blockType: 'hero', variant: 1, name: 'Hero Banner', description: 'Hero com headline grande, logos de clientes e stats' },
          { blockType: 'services', variant: 1, name: 'Cards Services', description: '4 cards de servicos com icones lime e numeros' },
          { blockType: 'gallery', variant: 1, name: 'Portfolio Cases', description: '3 cases de portfolio com imagens e descricao' },
          { blockType: 'about', variant: 1, name: 'About Carousel', description: 'Sobre nos com slider e 4 vantagens com icones' },
          { blockType: 'cta', variant: 1, name: 'CTA Green', description: 'CTA escuro com gradiente, headline e slider de depoimentos' },
          { blockType: 'services', variant: 2, name: 'Solutions Grid', description: '3 colunas de solucoes com categorias e outputs' },
          { blockType: 'testimonials', variant: 1, name: 'Testimonials Slider', description: 'Slider de depoimentos com nomes e cargos' },
          { blockType: 'footer', variant: 1, name: 'Footer Dark Green', description: 'Footer verde escuro com form, links, social e copyright' },
        ],
        availableVariants: {
          header: [1],
          hero: [1],
          services: [1, 2],
          gallery: [1],
          about: [1],
          cta: [1],
          testimonials: [1],
          footer: [1],
        },
        updatedAt: new Date(),
      },
    })

    console.log('✅ Template "Larko" criado/atualizado com sucesso!')
  } catch (error) {
    console.error('❌ Erro ao criar template:', error)
    throw error
  }
}

seedTemplates()
  .then(() => {
    console.log('🎉 Seed de templates concluido!')
    process.exit(0)
  })
  .catch((error) => {
    console.error('💥 Erro fatal no seed:', error)
    process.exit(1)
  })
