import 'dotenv/config'
import { db } from './index'
import { category } from './schema'

interface CategorySeed {
  name: string
  slug: string
  icon: string
  description: string
  suggestedServices: string[]
  seoTitle: string
  seoDescription: string
  seoKeywords: string[]
  heroTitle: string
  heroSubtitle: string
  longDescription: string
  faqs: Array<{ question: string; answer: string }>
}

const CATEGORIES_SEED: CategorySeed[] = [
  {
    name: 'Borracharia',
    slug: 'borracharia',
    icon: 'IconTire',
    description: 'Serviços de pneus, alinhamento e balanceamento',
    suggestedServices: ['Troca de Pneus', 'Reparo de Pneus', 'Alinhamento', 'Balanceamento', 'Calibragem', 'Socorro 24h'],
    seoTitle: 'Borracharias - Encontre a Melhor Perto de Você',
    seoDescription: 'Encontre as melhores borracharias da sua região. Troca de pneus, alinhamento, balanceamento e socorro 24h. Compare avaliações e preços.',
    seoKeywords: ['borracharia', 'troca de pneu', 'alinhamento', 'balanceamento', 'pneu furado', 'socorro 24h', 'calibragem'],
    heroTitle: 'Encontre a Melhor Borracharia',
    heroSubtitle: 'Compare avaliações, veja endereços e entre em contato diretamente pelo WhatsApp com as melhores borracharias da sua cidade.',
    longDescription: 'Precisa de serviços de borracharia? No Página Local você encontra as melhores borracharias da sua região, com avaliações reais de clientes, endereços completos e contato direto via WhatsApp. Seja para troca de pneus, alinhamento, balanceamento ou socorro 24h, conectamos você aos profissionais mais bem avaliados.',
    faqs: [
      { question: 'Quanto custa trocar um pneu?', answer: 'O valor da troca de pneu varia conforme o modelo e aro. Em média, o serviço de montagem e balanceamento custa entre R$ 30 e R$ 80 por pneu.' },
      { question: 'Com que frequência devo fazer alinhamento?', answer: 'Recomenda-se fazer alinhamento a cada 10.000 km ou sempre que notar o carro puxando para um lado.' },
      { question: 'Borracharia atende emergência?', answer: 'Muitas borracharias oferecem socorro 24h. Verifique nos perfis quais estabelecimentos oferecem este serviço.' },
    ],
  },
  {
    name: 'Oficina Mecânica',
    slug: 'oficina-mecanica',
    icon: 'IconTool',
    description: 'Manutenção e reparo de veículos',
    suggestedServices: ['Troca de Óleo', 'Revisão Completa', 'Freios', 'Suspensão', 'Motor', 'Diagnóstico'],
    seoTitle: 'Oficinas Mecânicas - Manutenção e Reparo',
    seoDescription: 'Encontre oficinas mecânicas confiáveis na sua cidade. Troca de óleo, revisão, freios, suspensão e mais. Avaliações reais de clientes.',
    seoKeywords: ['oficina mecânica', 'mecânico', 'troca de óleo', 'revisão', 'freios', 'suspensão', 'motor'],
    heroTitle: 'Encontre a Melhor Oficina Mecânica',
    heroSubtitle: 'Mecânicos de confiança para cuidar do seu carro. Veja avaliações, compare preços e agende sua revisão.',
    longDescription: 'Encontre oficinas mecânicas de confiança na sua região. No Página Local, você compara avaliações reais de clientes, vê os serviços oferecidos e entra em contato diretamente via WhatsApp. Desde troca de óleo até revisões completas, encontre o mecânico ideal para seu veículo.',
    faqs: [
      { question: 'Com que frequência devo trocar o óleo?', answer: 'O ideal é trocar o óleo a cada 5.000 a 10.000 km, dependendo do tipo de óleo e do veículo.' },
      { question: 'Quanto custa uma revisão completa?', answer: 'Uma revisão completa pode variar de R$ 200 a R$ 800, dependendo do veículo e dos itens incluídos.' },
      { question: 'Como escolher uma boa oficina?', answer: 'Verifique as avaliações de outros clientes, se a oficina é especializada no seu tipo de veículo e se oferece garantia nos serviços.' },
    ],
  },
  {
    name: 'Auto Center',
    slug: 'auto-center',
    icon: 'IconCar',
    description: 'Centro automotivo completo',
    suggestedServices: ['Manutenção Preventiva', 'Ar Condicionado', 'Elétrica', 'Injeção Eletrônica', 'Escapamento', 'Embreagem'],
    seoTitle: 'Auto Centers - Centro Automotivo Completo',
    seoDescription: 'Encontre auto centers com serviços completos: ar condicionado, elétrica, injeção eletrônica e mais. Compare e escolha o melhor.',
    seoKeywords: ['auto center', 'centro automotivo', 'ar condicionado automotivo', 'elétrica automotiva', 'injeção eletrônica'],
    heroTitle: 'Encontre o Melhor Auto Center',
    heroSubtitle: 'Centros automotivos completos com todos os serviços que seu carro precisa em um só lugar.',
    longDescription: 'Auto centers oferecem uma gama completa de serviços automotivos. Encontre os melhores da sua região no Página Local, com avaliações de clientes, lista de serviços e contato direto.',
    faqs: [
      { question: 'O que é um auto center?', answer: 'Um auto center é um estabelecimento que oferece diversos serviços automotivos em um só lugar, como mecânica, elétrica, ar condicionado e mais.' },
      { question: 'Auto center é mais caro que oficina?', answer: 'Não necessariamente. Auto centers podem ter preços competitivos e a vantagem de resolver tudo em um só lugar.' },
      { question: 'Posso fazer revisão em auto center?', answer: 'Sim, a maioria dos auto centers oferece revisão completa com todos os serviços necessários.' },
    ],
  },
  {
    name: 'Revendedora de Veículos',
    slug: 'revendedora-veiculos',
    icon: 'IconCarGarage',
    description: 'Compra e venda de veículos novos e seminovos',
    suggestedServices: ['Compra de Veículos', 'Venda de Seminovos', 'Financiamento', 'Consignação', 'Avaliação', 'Troca'],
    seoTitle: 'Revendedoras de Veículos - Compra e Venda',
    seoDescription: 'Encontre revendedoras de veículos confiáveis. Seminovos, financiamento, consignação e avaliação. Compare ofertas na sua cidade.',
    seoKeywords: ['revendedora', 'seminovos', 'carros usados', 'financiamento', 'consignação', 'compra de carro'],
    heroTitle: 'Encontre a Melhor Revendedora',
    heroSubtitle: 'Compre ou venda seu veículo com segurança. Revendedoras avaliadas por clientes reais.',
    longDescription: 'Procurando um seminovo de qualidade ou quer vender seu carro? Encontre as melhores revendedoras da sua região no Página Local. Compare avaliações, veja o estoque e negocie diretamente.',
    faqs: [
      { question: 'É seguro comprar em revendedora?', answer: 'Sim, desde que você escolha revendedoras bem avaliadas e verifique a documentação do veículo.' },
      { question: 'Revendedora faz financiamento?', answer: 'A maioria das revendedoras trabalha com diversas opções de financiamento facilitado.' },
      { question: 'Posso trocar meu carro?', answer: 'Sim, muitas revendedoras aceitam seu veículo usado como parte do pagamento.' },
    ],
  },
  {
    name: 'Lava Jato',
    slug: 'lava-jato',
    icon: 'IconDroplet',
    description: 'Lavagem e estética automotiva',
    suggestedServices: ['Lavagem Simples', 'Lavagem Completa', 'Polimento', 'Higienização', 'Cristalização', 'Enceramento'],
    seoTitle: 'Lava Jatos - Lavagem e Estética Automotiva',
    seoDescription: 'Encontre os melhores lava jatos da sua cidade. Lavagem completa, polimento, higienização e cristalização. Preços e avaliações.',
    seoKeywords: ['lava jato', 'lavagem de carro', 'polimento', 'higienização', 'cristalização', 'enceramento'],
    heroTitle: 'Encontre o Melhor Lava Jato',
    heroSubtitle: 'Deixe seu carro brilhando! Compare lava jatos com os melhores serviços e preços.',
    longDescription: 'Mantenha seu carro sempre limpo e bem cuidado. Encontre lava jatos de qualidade na sua região, com serviços de lavagem simples até estética automotiva completa.',
    faqs: [
      { question: 'Quanto custa lavar o carro?', answer: 'Uma lavagem simples custa em média R$ 30 a R$ 50. Lavagem completa varia de R$ 60 a R$ 150.' },
      { question: 'O que é cristalização?', answer: 'É um tratamento que protege a pintura do carro, criando uma camada protetora contra riscos e raios UV.' },
      { question: 'Com que frequência devo lavar o carro?', answer: 'Recomenda-se lavar a cada 15 dias ou semanalmente se o carro fica exposto a muita sujeira.' },
    ],
  },
  {
    name: 'Estacionamento',
    slug: 'estacionamento',
    icon: 'IconParking',
    description: 'Vagas de estacionamento',
    suggestedServices: ['Vaga Rotativa', 'Mensalista', 'Lavagem', 'Manobrista', 'Segurança 24h'],
    seoTitle: 'Estacionamentos - Vagas Seguras',
    seoDescription: 'Encontre estacionamentos seguros na sua cidade. Vagas rotativas, mensalistas, com manobrista e segurança 24h.',
    seoKeywords: ['estacionamento', 'vaga', 'mensalista', 'manobrista', 'estacionamento seguro'],
    heroTitle: 'Encontre Estacionamentos Seguros',
    heroSubtitle: 'Vagas rotativas ou mensais com segurança e praticidade.',
    longDescription: 'Encontre estacionamentos confiáveis e seguros na sua região. Compare preços, veja os serviços oferecidos e escolha o melhor para suas necessidades.',
    faqs: [
      { question: 'Quanto custa estacionamento mensal?', answer: 'O valor mensal varia conforme a localização, geralmente entre R$ 200 e R$ 600.' },
      { question: 'Estacionamento tem seguro?', answer: 'A maioria dos estacionamentos possui seguro contra roubo e danos, mas verifique as condições.' },
      { question: 'Posso deixar o carro 24h?', answer: 'Muitos estacionamentos oferecem serviço 24h, especialmente os mensalistas.' },
    ],
  },
  {
    name: 'Barbearia',
    slug: 'barbearia',
    icon: 'IconScissors',
    description: 'Cortes masculinos e barba',
    suggestedServices: ['Corte de Cabelo', 'Barba', 'Sobrancelha', 'Hidratação', 'Pigmentação', 'Combo Completo'],
    seoTitle: 'Barbearias - Corte e Barba Masculina',
    seoDescription: 'Encontre as melhores barbearias da sua cidade. Corte masculino, barba, sobrancelha e tratamentos. Veja avaliações e agende.',
    seoKeywords: ['barbearia', 'corte masculino', 'barba', 'barbeiro', 'corte de cabelo', 'barbearia perto de mim'],
    heroTitle: 'Encontre a Melhor Barbearia',
    heroSubtitle: 'Corte e barba com os melhores barbeiros. Agende pelo WhatsApp!',
    longDescription: 'Encontre barbearias de qualidade na sua região. No Página Local, você vê fotos dos trabalhos, avaliações de clientes e agenda direto pelo WhatsApp.',
    faqs: [
      { question: 'Quanto custa um corte de cabelo?', answer: 'O corte masculino em barbearias varia de R$ 25 a R$ 80, dependendo do estabelecimento.' },
      { question: 'Precisa agendar horário?', answer: 'Recomendamos agendar, especialmente em barbearias muito procuradas. Entre em contato via WhatsApp.' },
      { question: 'Barbearia faz barba?', answer: 'Sim, a maioria das barbearias oferece serviço de barba com navalha e acabamento profissional.' },
    ],
  },
  {
    name: 'Salão de Beleza',
    slug: 'salao-beleza',
    icon: 'IconSparkles',
    description: 'Serviços de beleza e estética',
    suggestedServices: ['Corte Feminino', 'Coloração', 'Escova', 'Manicure', 'Pedicure', 'Design de Sobrancelha'],
    seoTitle: 'Salões de Beleza - Beleza e Estética',
    seoDescription: 'Encontre os melhores salões de beleza. Corte, coloração, manicure, pedicure e mais. Compare avaliações e agende seu horário.',
    seoKeywords: ['salão de beleza', 'cabeleireiro', 'manicure', 'pedicure', 'coloração', 'escova'],
    heroTitle: 'Encontre o Melhor Salão de Beleza',
    heroSubtitle: 'Cabelo, unhas e estética com profissionais qualificados. Agende agora!',
    longDescription: 'Encontre salões de beleza de qualidade na sua região. Veja fotos dos trabalhos, avaliações de clientes e agende seus serviços diretamente.',
    faqs: [
      { question: 'Quanto custa coloração?', answer: 'O valor da coloração varia de R$ 80 a R$ 300, dependendo do comprimento e técnica utilizada.' },
      { question: 'Salão faz design de sobrancelha?', answer: 'Sim, a maioria dos salões oferece design de sobrancelha com diversos métodos.' },
      { question: 'Precisa agendar horário?', answer: 'Sim, é importante agendar para garantir seu horário, especialmente para procedimentos demorados.' },
    ],
  },
  {
    name: 'Restaurante',
    slug: 'restaurante',
    icon: 'IconToolsKitchen2',
    description: 'Gastronomia e alimentação',
    suggestedServices: ['Almoço Executivo', 'Self-Service', 'À la Carte', 'Delivery', 'Eventos', 'Marmitex'],
    seoTitle: 'Restaurantes - Onde Comer Bem',
    seoDescription: 'Encontre os melhores restaurantes da sua cidade. Self-service, à la carte, delivery e mais. Veja avaliações e cardápios.',
    seoKeywords: ['restaurante', 'onde comer', 'almoço', 'self-service', 'delivery', 'comida'],
    heroTitle: 'Encontre os Melhores Restaurantes',
    heroSubtitle: 'Descubra onde comer bem na sua cidade. Avaliações reais e contato direto.',
    longDescription: 'Encontre restaurantes de qualidade na sua região. Seja para um almoço executivo, jantar especial ou delivery, compare opções e escolha o melhor.',
    faqs: [
      { question: 'Restaurante faz delivery?', answer: 'Muitos restaurantes oferecem delivery. Verifique no perfil de cada estabelecimento.' },
      { question: 'Quanto custa almoço executivo?', answer: 'O almoço executivo geralmente varia de R$ 20 a R$ 50, dependendo do restaurante.' },
      { question: 'Posso reservar mesa?', answer: 'A maioria dos restaurantes aceita reservas. Entre em contato via WhatsApp para confirmar.' },
    ],
  },
  {
    name: 'Pizzaria',
    slug: 'pizzaria',
    icon: 'IconPizza',
    description: 'Pizzas artesanais e delivery',
    suggestedServices: ['Pizzas Tradicionais', 'Pizzas Especiais', 'Rodízio', 'Delivery', 'Calzones', 'Esfihas'],
    seoTitle: 'Pizzarias - As Melhores Pizzas',
    seoDescription: 'Encontre as melhores pizzarias da sua cidade. Pizzas artesanais, rodízio e delivery. Veja avaliações e peça agora!',
    seoKeywords: ['pizzaria', 'pizza', 'delivery pizza', 'rodízio pizza', 'pizza artesanal'],
    heroTitle: 'Encontre as Melhores Pizzarias',
    heroSubtitle: 'Pizzas deliciosas com delivery ou para comer no local. Compare e peça!',
    longDescription: 'Descubra as melhores pizzarias da sua região. Compare avaliações, veja o cardápio e peça sua pizza favorita.',
    faqs: [
      { question: 'Pizzaria entrega?', answer: 'A maioria das pizzarias oferece delivery. Verifique a área de entrega e tempo estimado.' },
      { question: 'Quanto custa uma pizza grande?', answer: 'Pizzas grandes variam de R$ 40 a R$ 100, dependendo dos sabores e da pizzaria.' },
      { question: 'Pizzaria tem rodízio?', answer: 'Algumas pizzarias oferecem rodízio. Verifique no perfil do estabelecimento.' },
    ],
  },
  {
    name: 'Lanchonete',
    slug: 'lanchonete',
    icon: 'IconBurger',
    description: 'Lanches rápidos e sanduíches',
    suggestedServices: ['Lanches', 'Sanduíches', 'Porções', 'Sucos', 'Açaí', 'Combos'],
    seoTitle: 'Lanchonetes - Lanches e Sanduíches',
    seoDescription: 'Encontre as melhores lanchonetes da sua cidade. Hambúrgueres, sanduíches, porções e mais. Avaliações e delivery.',
    seoKeywords: ['lanchonete', 'hambúrguer', 'sanduíche', 'lanche', 'fast food', 'açaí'],
    heroTitle: 'Encontre as Melhores Lanchonetes',
    heroSubtitle: 'Lanches saborosos e rápidos. Veja avaliações e peça agora!',
    longDescription: 'Encontre lanchonetes de qualidade na sua região. Hambúrgueres artesanais, sanduíches e muito mais.',
    faqs: [
      { question: 'Lanchonete faz delivery?', answer: 'A maioria das lanchonetes oferece delivery. Verifique no perfil do estabelecimento.' },
      { question: 'Quanto custa um hambúrguer?', answer: 'Hambúrgueres variam de R$ 15 a R$ 45, dependendo do tamanho e ingredientes.' },
      { question: 'Tem opções vegetarianas?', answer: 'Muitas lanchonetes oferecem opções vegetarianas. Consulte o cardápio.' },
    ],
  },
  {
    name: 'Padaria',
    slug: 'padaria',
    icon: 'IconBread',
    description: 'Pães artesanais e confeitaria',
    suggestedServices: ['Pães Artesanais', 'Bolos', 'Salgados', 'Café da Manhã', 'Encomendas', 'Frios'],
    seoTitle: 'Padarias - Pães e Confeitaria',
    seoDescription: 'Encontre as melhores padarias da sua cidade. Pães artesanais, bolos, salgados e café da manhã. Veja avaliações.',
    seoKeywords: ['padaria', 'pão', 'bolo', 'confeitaria', 'café da manhã', 'salgados'],
    heroTitle: 'Encontre as Melhores Padarias',
    heroSubtitle: 'Pães fresquinhos, bolos e muito mais. Descubra as melhores padarias!',
    longDescription: 'Encontre padarias de qualidade na sua região. Pães artesanais, confeitaria e café da manhã completo.',
    faqs: [
      { question: 'Padaria faz encomenda de bolo?', answer: 'Sim, a maioria das padarias aceita encomendas de bolos para festas e eventos.' },
      { question: 'Tem café da manhã?', answer: 'Muitas padarias servem café da manhã completo. Verifique o horário de funcionamento.' },
      { question: 'Padaria entrega?', answer: 'Algumas padarias oferecem delivery. Consulte o perfil do estabelecimento.' },
    ],
  },
  {
    name: 'Pet Shop',
    slug: 'pet-shop',
    icon: 'IconDog',
    description: 'Produtos e serviços para pets',
    suggestedServices: ['Banho', 'Tosa', 'Ração', 'Acessórios', 'Veterinário', 'Hotel Pet'],
    seoTitle: 'Pet Shops - Cuidados com seu Pet',
    seoDescription: 'Encontre os melhores pet shops da sua cidade. Banho, tosa, ração, acessórios e mais. Cuide bem do seu pet!',
    seoKeywords: ['pet shop', 'banho e tosa', 'ração', 'veterinário', 'hotel pet', 'acessórios pet'],
    heroTitle: 'Encontre o Melhor Pet Shop',
    heroSubtitle: 'Tudo para o seu pet em um só lugar. Banho, tosa, ração e muito mais!',
    longDescription: 'Encontre pet shops de confiança na sua região. Serviços de banho e tosa, rações de qualidade e acessórios para seu pet.',
    faqs: [
      { question: 'Quanto custa banho e tosa?', answer: 'O valor varia conforme o porte do animal, geralmente de R$ 40 a R$ 150.' },
      { question: 'Pet shop tem veterinário?', answer: 'Alguns pet shops contam com atendimento veterinário. Verifique no perfil.' },
      { question: 'Tem hotel para pets?', answer: 'Muitos pet shops oferecem hospedagem. Consulte disponibilidade e valores.' },
    ],
  },
  {
    name: 'Clínica Veterinária',
    slug: 'clinica-veterinaria',
    icon: 'IconStethoscope',
    description: 'Atendimento veterinário',
    suggestedServices: ['Consultas', 'Vacinas', 'Exames', 'Cirurgias', 'Emergência', 'Internação'],
    seoTitle: 'Clínicas Veterinárias - Saúde do seu Pet',
    seoDescription: 'Encontre clínicas veterinárias de confiança. Consultas, vacinas, exames e emergência. Cuide da saúde do seu pet!',
    seoKeywords: ['veterinário', 'clínica veterinária', 'vacina pet', 'emergência pet', 'castração'],
    heroTitle: 'Encontre Clínicas Veterinárias',
    heroSubtitle: 'Veterinários de confiança para cuidar da saúde do seu pet.',
    longDescription: 'Encontre clínicas veterinárias de qualidade na sua região. Atendimento completo para a saúde do seu animal de estimação.',
    faqs: [
      { question: 'Quanto custa consulta veterinária?', answer: 'Consultas veterinárias variam de R$ 80 a R$ 200, dependendo da clínica e especialidade.' },
      { question: 'Clínica atende emergência?', answer: 'Algumas clínicas oferecem atendimento 24h. Verifique no perfil do estabelecimento.' },
      { question: 'Quanto custa castração?', answer: 'O valor da castração varia de R$ 200 a R$ 800, conforme o porte e sexo do animal.' },
    ],
  },
  {
    name: 'Clínica Médica',
    slug: 'clinica-medica',
    icon: 'IconHeartbeat',
    description: 'Atendimento médico especializado',
    suggestedServices: ['Consultas', 'Exames', 'Check-up', 'Especialidades', 'Procedimentos', 'Telemedicina'],
    seoTitle: 'Clínicas Médicas - Saúde e Bem-estar',
    seoDescription: 'Encontre clínicas médicas de qualidade. Consultas, exames, especialidades e mais. Cuide da sua saúde!',
    seoKeywords: ['clínica médica', 'médico', 'consulta', 'exames', 'especialista', 'check-up'],
    heroTitle: 'Encontre Clínicas Médicas',
    heroSubtitle: 'Médicos especialistas para cuidar da sua saúde. Agende sua consulta!',
    longDescription: 'Encontre clínicas médicas de confiança na sua região. Diversas especialidades e exames para cuidar da sua saúde.',
    faqs: [
      { question: 'Clínica aceita convênio?', answer: 'Muitas clínicas aceitam diversos convênios. Verifique no perfil do estabelecimento.' },
      { question: 'Como agendar consulta?', answer: 'Entre em contato via WhatsApp ou telefone para agendar sua consulta.' },
      { question: 'Clínica faz exames?', answer: 'A maioria das clínicas oferece exames laboratoriais e de imagem.' },
    ],
  },
  {
    name: 'Consultório Odontológico',
    slug: 'consultorio-odontologico',
    icon: 'IconDental',
    description: 'Serviços odontológicos',
    suggestedServices: ['Limpeza', 'Restauração', 'Canal', 'Clareamento', 'Implantes', 'Ortodontia'],
    seoTitle: 'Dentistas e Consultórios Odontológicos',
    seoDescription: 'Encontre dentistas de qualidade. Limpeza, clareamento, implantes, ortodontia e mais. Agende sua consulta!',
    seoKeywords: ['dentista', 'consultório odontológico', 'clareamento', 'implante', 'ortodontia', 'canal'],
    heroTitle: 'Encontre Dentistas de Qualidade',
    heroSubtitle: 'Cuide do seu sorriso com os melhores dentistas da região.',
    longDescription: 'Encontre consultórios odontológicos de confiança. Tratamentos completos para a saúde e estética do seu sorriso.',
    faqs: [
      { question: 'Quanto custa limpeza dental?', answer: 'A limpeza dental varia de R$ 100 a R$ 300, dependendo do consultório.' },
      { question: 'Quanto custa clareamento?', answer: 'O clareamento dental varia de R$ 400 a R$ 1.500, conforme a técnica utilizada.' },
      { question: 'Dentista faz implante?', answer: 'Muitos consultórios oferecem implantes. Verifique as especialidades disponíveis.' },
    ],
  },
  {
    name: 'Academia',
    slug: 'academia',
    icon: 'IconBarbell',
    description: 'Musculação e atividades físicas',
    suggestedServices: ['Musculação', 'Aeróbico', 'Personal Trainer', 'Spinning', 'Funcional', 'Crossfit'],
    seoTitle: 'Academias - Musculação e Fitness',
    seoDescription: 'Encontre as melhores academias da sua cidade. Musculação, funcional, crossfit, spinning e mais. Compare e matricule-se!',
    seoKeywords: ['academia', 'musculação', 'fitness', 'crossfit', 'personal trainer', 'funcional'],
    heroTitle: 'Encontre a Melhor Academia',
    heroSubtitle: 'Alcance seus objetivos fitness com as melhores academias da região.',
    longDescription: 'Encontre academias de qualidade na sua região. Compare estrutura, modalidades e valores para escolher a ideal para você.',
    faqs: [
      { question: 'Quanto custa academia por mês?', answer: 'Mensalidades variam de R$ 60 a R$ 300, dependendo da estrutura e serviços oferecidos.' },
      { question: 'Academia tem personal trainer?', answer: 'Muitas academias oferecem personal trainer como serviço adicional.' },
      { question: 'Posso fazer aula experimental?', answer: 'A maioria das academias oferece aula experimental gratuita. Entre em contato para agendar.' },
    ],
  },
  {
    name: 'Farmácia',
    slug: 'farmacia',
    icon: 'IconPill',
    description: 'Medicamentos e produtos de saúde',
    suggestedServices: ['Medicamentos', 'Perfumaria', 'Dermocosméticos', 'Manipulados', 'Delivery', 'Aferição'],
    seoTitle: 'Farmácias - Medicamentos e Saúde',
    seoDescription: 'Encontre farmácias na sua cidade. Medicamentos, perfumaria, manipulados e delivery. Preços e localização.',
    seoKeywords: ['farmácia', 'medicamento', 'drogaria', 'farmácia 24h', 'delivery farmácia'],
    heroTitle: 'Encontre Farmácias Perto de Você',
    heroSubtitle: 'Medicamentos e produtos de saúde com entrega rápida.',
    longDescription: 'Encontre farmácias na sua região. Compare preços, veja horários de funcionamento e peça delivery.',
    faqs: [
      { question: 'Farmácia entrega?', answer: 'Muitas farmácias oferecem delivery. Verifique disponibilidade e área de entrega.' },
      { question: 'Tem farmácia 24h?', answer: 'Algumas farmácias funcionam 24h. Verifique o horário no perfil do estabelecimento.' },
      { question: 'Farmácia faz manipulação?', answer: 'Farmácias de manipulação preparam medicamentos personalizados sob prescrição.' },
    ],
  },
  {
    name: 'Supermercado',
    slug: 'supermercado',
    icon: 'IconShoppingCart',
    description: 'Produtos alimentícios e de limpeza',
    suggestedServices: ['Hortifruti', 'Açougue', 'Padaria', 'Frios', 'Delivery', 'Atacado'],
    seoTitle: 'Supermercados - Compras do Dia a Dia',
    seoDescription: 'Encontre supermercados na sua cidade. Hortifruti, açougue, padaria e delivery. Compare preços e ofertas.',
    seoKeywords: ['supermercado', 'mercado', 'hortifruti', 'açougue', 'delivery mercado'],
    heroTitle: 'Encontre Supermercados',
    heroSubtitle: 'Faça suas compras nos melhores supermercados da região.',
    longDescription: 'Encontre supermercados de qualidade na sua região. Compare preços, veja ofertas e peça delivery.',
    faqs: [
      { question: 'Supermercado entrega?', answer: 'Muitos supermercados oferecem delivery. Verifique disponibilidade e valor mínimo.' },
      { question: 'Tem atacado?', answer: 'Alguns supermercados trabalham com preços de atacado para compras em quantidade.' },
      { question: 'Aceita cartão?', answer: 'A maioria dos supermercados aceita cartões de crédito e débito.' },
    ],
  },
  {
    name: 'Imobiliária',
    slug: 'imobiliaria',
    icon: 'IconHome',
    description: 'Compra, venda e aluguel de imóveis',
    suggestedServices: ['Venda de Imóveis', 'Aluguel', 'Administração', 'Avaliação', 'Documentação', 'Financiamento'],
    seoTitle: 'Imobiliárias - Compra e Aluguel',
    seoDescription: 'Encontre imobiliárias de confiança. Compra, venda e aluguel de imóveis. Veja opções e entre em contato.',
    seoKeywords: ['imobiliária', 'aluguel', 'compra de imóvel', 'apartamento', 'casa', 'corretor'],
    heroTitle: 'Encontre Imobiliárias de Confiança',
    heroSubtitle: 'Seu próximo imóvel está aqui. Compra, venda ou aluguel.',
    longDescription: 'Encontre imobiliárias de confiança na sua região. Compare opções de imóveis para compra, venda ou aluguel.',
    faqs: [
      { question: 'Como funciona aluguel?', answer: 'O aluguel envolve análise de crédito, contrato e geralmente um depósito caução ou fiador.' },
      { question: 'Imobiliária cobra taxa?', answer: 'Geralmente a taxa de corretagem é paga pelo vendedor na venda e pelo locador no aluguel.' },
      { question: 'Posso financiar imóvel?', answer: 'Sim, muitas imobiliárias auxiliam no processo de financiamento bancário.' },
    ],
  },
  {
    name: 'Escritório de Advocacia',
    slug: 'escritorio-advocacia',
    icon: 'IconScale',
    description: 'Serviços jurídicos',
    suggestedServices: ['Consultoria', 'Trabalhista', 'Cível', 'Criminal', 'Empresarial', 'Família'],
    seoTitle: 'Advogados e Escritórios de Advocacia',
    seoDescription: 'Encontre advogados de confiança. Direito trabalhista, cível, criminal, família e mais. Consultoria jurídica.',
    seoKeywords: ['advogado', 'escritório advocacia', 'direito trabalhista', 'direito família', 'consultoria jurídica'],
    heroTitle: 'Encontre Advogados de Confiança',
    heroSubtitle: 'Assessoria jurídica para todas as suas necessidades.',
    longDescription: 'Encontre escritórios de advocacia de confiança. Diversas especialidades para resolver suas questões jurídicas.',
    faqs: [
      { question: 'Quanto custa consulta com advogado?', answer: 'Consultas variam de R$ 150 a R$ 500. Alguns escritórios oferecem primeira consulta gratuita.' },
      { question: 'Advogado atende online?', answer: 'Muitos escritórios oferecem atendimento online para consultas e acompanhamento de processos.' },
      { question: 'Como escolher um advogado?', answer: 'Verifique a especialidade, experiência e avaliações de outros clientes.' },
    ],
  },
  {
    name: 'Escritório de Contabilidade',
    slug: 'escritorio-contabilidade',
    icon: 'IconCalculator',
    description: 'Serviços contábeis e fiscais',
    suggestedServices: ['Abertura de Empresa', 'Contabilidade', 'Folha de Pagamento', 'Impostos', 'Consultoria', 'BPO'],
    seoTitle: 'Contadores e Escritórios de Contabilidade',
    seoDescription: 'Encontre contadores de confiança. Abertura de empresa, impostos, folha de pagamento e mais. Assessoria contábil.',
    seoKeywords: ['contador', 'contabilidade', 'abertura de empresa', 'imposto de renda', 'MEI', 'CNPJ'],
    heroTitle: 'Encontre Contadores de Confiança',
    heroSubtitle: 'Assessoria contábil completa para sua empresa ou pessoa física.',
    longDescription: 'Encontre escritórios de contabilidade de qualidade. Serviços completos para empresas e pessoas físicas.',
    faqs: [
      { question: 'Quanto custa abrir uma empresa?', answer: 'O custo varia conforme o tipo de empresa, geralmente de R$ 500 a R$ 2.000 incluindo taxas.' },
      { question: 'Contador ajuda com imposto de renda?', answer: 'Sim, contadores auxiliam na declaração de imposto de renda pessoa física e jurídica.' },
      { question: 'Como funciona contabilidade mensal?', answer: 'O contador cuida de todas as obrigações fiscais e contábeis da sua empresa mensalmente.' },
    ],
  },
  {
    name: 'Escola',
    slug: 'escola',
    icon: 'IconSchool',
    description: 'Instituição de ensino',
    suggestedServices: ['Educação Infantil', 'Ensino Fundamental', 'Ensino Médio', 'Reforço', 'Cursos', 'Atividades'],
    seoTitle: 'Escolas - Educação de Qualidade',
    seoDescription: 'Encontre as melhores escolas da sua cidade. Educação infantil, fundamental, médio e cursos. Compare e matricule!',
    seoKeywords: ['escola', 'colégio', 'educação infantil', 'ensino fundamental', 'matrícula', 'curso'],
    heroTitle: 'Encontre as Melhores Escolas',
    heroSubtitle: 'Educação de qualidade para todas as idades.',
    longDescription: 'Encontre escolas de qualidade na sua região. Compare metodologias, estrutura e valores para escolher a melhor.',
    faqs: [
      { question: 'Como fazer matrícula?', answer: 'Entre em contato com a escola para conhecer o processo de matrícula e documentos necessários.' },
      { question: 'Escola oferece período integral?', answer: 'Muitas escolas oferecem período integral. Verifique no perfil do estabelecimento.' },
      { question: 'Tem aula de reforço?', answer: 'Algumas escolas oferecem aulas de reforço e apoio pedagógico.' },
    ],
  },
  {
    name: 'Hotel',
    slug: 'hotel',
    icon: 'IconBed',
    description: 'Hospedagem e eventos',
    suggestedServices: ['Hospedagem', 'Eventos', 'Restaurante', 'Day Use', 'Transfer', 'Estacionamento'],
    seoTitle: 'Hotéis e Pousadas - Hospedagem',
    seoDescription: 'Encontre hotéis e pousadas na sua cidade. Compare preços, estrutura e avaliações. Reserve sua estadia!',
    seoKeywords: ['hotel', 'pousada', 'hospedagem', 'reserva hotel', 'diária', 'estadia'],
    heroTitle: 'Encontre Hotéis e Pousadas',
    heroSubtitle: 'Hospedagem confortável para sua viagem ou evento.',
    longDescription: 'Encontre hotéis e pousadas de qualidade na região. Compare estrutura, serviços e valores.',
    faqs: [
      { question: 'Como reservar?', answer: 'Entre em contato via WhatsApp ou telefone para verificar disponibilidade e fazer sua reserva.' },
      { question: 'Hotel tem estacionamento?', answer: 'Muitos hotéis oferecem estacionamento gratuito ou pago. Verifique no perfil.' },
      { question: 'Aceita pets?', answer: 'Alguns hotéis aceitam animais de estimação. Consulte antes de reservar.' },
    ],
  },
  {
    name: 'Floricultura',
    slug: 'floricultura',
    icon: 'IconFlower',
    description: 'Flores e arranjos',
    suggestedServices: ['Buquês', 'Arranjos', 'Coroas', 'Plantas', 'Decoração', 'Delivery'],
    seoTitle: 'Floriculturas - Flores e Arranjos',
    seoDescription: 'Encontre floriculturas na sua cidade. Buquês, arranjos, coroas e plantas. Delivery para presentear quem você ama!',
    seoKeywords: ['floricultura', 'flores', 'buquê', 'arranjo', 'coroa de flores', 'plantas'],
    heroTitle: 'Encontre as Melhores Floriculturas',
    heroSubtitle: 'Flores e arranjos para todas as ocasiões. Delivery disponível!',
    longDescription: 'Encontre floriculturas de qualidade na sua região. Buquês, arranjos, coroas e plantas para presentear.',
    faqs: [
      { question: 'Floricultura entrega?', answer: 'A maioria das floriculturas oferece delivery. Verifique área e horários de entrega.' },
      { question: 'Quanto custa um buquê?', answer: 'Buquês variam de R$ 50 a R$ 300, dependendo das flores e tamanho.' },
      { question: 'Faz decoração de eventos?', answer: 'Muitas floriculturas oferecem serviço de decoração para casamentos e eventos.' },
    ],
  },
  // ========== NOVAS CATEGORIAS - VAREJO E COMÉRCIO ==========
  {
    name: 'Loja de Roupas',
    slug: 'loja-de-roupas',
    icon: 'IconShirt',
    description: 'Moda feminina, masculina e infantil',
    suggestedServices: ['Moda Feminina', 'Moda Masculina', 'Moda Infantil', 'Acessórios', 'Plus Size', 'Ajustes'],
    seoTitle: 'Lojas de Roupas - Moda Perto de Você',
    seoDescription: 'Encontre as melhores lojas de roupas da sua cidade. Moda feminina, masculina e infantil. Compare preços e avaliações.',
    seoKeywords: ['loja de roupas', 'moda', 'vestuário', 'roupas femininas', 'roupas masculinas', 'roupa infantil', 'boutique'],
    heroTitle: 'Encontre a Melhor Loja de Roupas',
    heroSubtitle: 'Moda para todos os estilos. Compare lojas, veja avaliações e encontre looks incríveis!',
    longDescription: 'Encontre lojas de roupas de qualidade na sua região. Moda feminina, masculina, infantil e plus size. Compare preços, veja fotos e entre em contato diretamente.',
    faqs: [
      { question: 'Loja de roupas faz ajustes?', answer: 'Muitas lojas oferecem serviço de ajustes ou indicam costureiras parceiras.' },
      { question: 'Tem provador?', answer: 'A maioria das lojas físicas oferece provadores. Verifique no perfil do estabelecimento.' },
      { question: 'Aceita troca?', answer: 'Políticas de troca variam por loja. Consulte as condições antes da compra.' },
    ],
  },
  {
    name: 'Moda e Eventos',
    slug: 'moda-e-eventos',
    icon: 'IconHanger',
    description: 'Vestidos de noiva, festa e aluguel',
    suggestedServices: ['Vestido de Noiva', 'Vestido de Festa', 'Aluguel', 'Traje Masculino', 'Daminha e Pajem', 'Acessórios'],
    seoTitle: 'Moda para Eventos - Noivas e Festas',
    seoDescription: 'Encontre lojas especializadas em moda para eventos. Vestidos de noiva, festa, aluguel de trajes e acessórios.',
    seoKeywords: ['vestido de noiva', 'vestido de festa', 'aluguel de vestido', 'noiva', 'casamento', 'formatura', 'debutante'],
    heroTitle: 'Encontre Moda para seu Evento',
    heroSubtitle: 'Vestidos de noiva, festa, formaturas e aluguel de trajes. Realize seu sonho!',
    longDescription: 'Encontre lojas especializadas em moda para eventos especiais. Vestidos de noiva, festa, formaturas, debutantes e aluguel de trajes masculinos.',
    faqs: [
      { question: 'Quanto custa vestido de noiva?', answer: 'Vestidos de noiva variam de R$ 1.000 a R$ 15.000+, dependendo do modelo e marca.' },
      { question: 'Posso alugar vestido?', answer: 'Sim, muitas lojas oferecem aluguel de vestidos de festa e trajes. É uma opção econômica.' },
      { question: 'Com quanto tempo de antecedência devo escolher?', answer: 'Para noivas, recomenda-se 6 a 12 meses. Para festas, 1 a 3 meses.' },
    ],
  },
  {
    name: 'Loja de Eletrônicos',
    slug: 'loja-de-eletronicos',
    icon: 'IconDeviceMobile',
    description: 'Celulares, computadores e eletrônicos',
    suggestedServices: ['Celulares', 'Computadores', 'Acessórios', 'Assistência Técnica', 'Games', 'Smart Home'],
    seoTitle: 'Lojas de Eletrônicos - Tecnologia',
    seoDescription: 'Encontre lojas de eletrônicos na sua cidade. Celulares, computadores, games e acessórios. Compare preços e avaliações.',
    seoKeywords: ['loja de eletrônicos', 'celular', 'smartphone', 'computador', 'notebook', 'games', 'acessórios'],
    heroTitle: 'Encontre Lojas de Eletrônicos',
    heroSubtitle: 'Tecnologia de ponta com os melhores preços. Compare e compre!',
    longDescription: 'Encontre lojas de eletrônicos de confiança. Celulares, computadores, notebooks, games e acessórios com garantia.',
    faqs: [
      { question: 'Loja oferece garantia?', answer: 'A maioria das lojas oferece garantia do fabricante mais garantia estendida opcional.' },
      { question: 'Faz assistência técnica?', answer: 'Muitas lojas oferecem assistência técnica para os produtos vendidos.' },
      { question: 'Aceita troca de aparelho?', answer: 'Algumas lojas aceitam seu aparelho usado como parte do pagamento.' },
    ],
  },
  {
    name: 'Loja de Móveis',
    slug: 'loja-de-moveis',
    icon: 'IconArmchair',
    description: 'Móveis para casa e escritório',
    suggestedServices: ['Móveis Planejados', 'Sofás', 'Camas', 'Mesas', 'Móveis de Escritório', 'Decoração'],
    seoTitle: 'Lojas de Móveis - Casa e Escritório',
    seoDescription: 'Encontre lojas de móveis na sua cidade. Móveis planejados, sofás, camas e decoração. Compare preços e qualidade.',
    seoKeywords: ['loja de móveis', 'móveis planejados', 'sofá', 'cama', 'mesa', 'decoração', 'móveis escritório'],
    heroTitle: 'Encontre Lojas de Móveis',
    heroSubtitle: 'Móveis de qualidade para sua casa ou escritório. Compare e escolha!',
    longDescription: 'Encontre lojas de móveis na sua região. Móveis planejados, prontos, sofás, camas e muito mais com entrega e montagem.',
    faqs: [
      { question: 'Loja entrega e monta?', answer: 'A maioria das lojas oferece serviço de entrega e montagem inclusos ou como adicional.' },
      { question: 'Faz móveis sob medida?', answer: 'Muitas lojas trabalham com móveis planejados e sob medida.' },
      { question: 'Quanto tempo para entregar?', answer: 'Móveis prontos: 3-7 dias. Planejados: 30-60 dias dependendo do projeto.' },
    ],
  },
  {
    name: 'Loja de Ferragens',
    slug: 'loja-de-ferragens',
    icon: 'IconHammer',
    description: 'Ferramentas e materiais de construção',
    suggestedServices: ['Ferramentas', 'Parafusos', 'Tintas', 'Elétrica', 'Hidráulica', 'EPI'],
    seoTitle: 'Lojas de Ferragens - Ferramentas e Materiais',
    seoDescription: 'Encontre lojas de ferragens na sua cidade. Ferramentas, materiais de construção, tintas e muito mais.',
    seoKeywords: ['loja de ferragens', 'ferramentas', 'material construção', 'tintas', 'parafusos', 'ferragem'],
    heroTitle: 'Encontre Lojas de Ferragens',
    heroSubtitle: 'Tudo para sua obra ou reparo. Ferramentas e materiais de qualidade!',
    longDescription: 'Encontre lojas de ferragens completas na sua região. Ferramentas, materiais de construção, tintas, elétrica e hidráulica.',
    faqs: [
      { question: 'Loja entrega?', answer: 'Muitas lojas de ferragens oferecem delivery para compras acima de determinado valor.' },
      { question: 'Tem material elétrico?', answer: 'Sim, a maioria das lojas tem seção completa de materiais elétricos.' },
      { question: 'Vende por atacado?', answer: 'Algumas lojas oferecem preços especiais para compras em quantidade.' },
    ],
  },
  {
    name: 'Loja de Decoração',
    slug: 'loja-de-decoracao',
    icon: 'IconLamp',
    description: 'Decoração e artigos para casa',
    suggestedServices: ['Objetos Decorativos', 'Quadros', 'Iluminação', 'Tapetes', 'Cortinas', 'Utensílios'],
    seoTitle: 'Lojas de Decoração - Artigos para Casa',
    seoDescription: 'Encontre lojas de decoração na sua cidade. Objetos decorativos, quadros, iluminação e utensílios para sua casa.',
    seoKeywords: ['loja de decoração', 'decoração casa', 'objetos decorativos', 'quadros', 'iluminação', 'tapetes'],
    heroTitle: 'Encontre Lojas de Decoração',
    heroSubtitle: 'Transforme sua casa com peças únicas de decoração!',
    longDescription: 'Encontre lojas de decoração na sua região. Objetos decorativos, quadros, iluminação, tapetes e muito mais para deixar sua casa ainda mais bonita.',
    faqs: [
      { question: 'Loja faz projeto de decoração?', answer: 'Algumas lojas oferecem consultoria de decoração gratuita ou paga.' },
      { question: 'Tem produtos importados?', answer: 'Muitas lojas trabalham com produtos nacionais e importados.' },
      { question: 'Faz lista de casamento?', answer: 'Algumas lojas de decoração oferecem serviço de lista de casamento.' },
    ],
  },
  {
    name: 'Joalheria',
    slug: 'joalheria',
    icon: 'IconDiamond',
    description: 'Joias, relógios e acessórios',
    suggestedServices: ['Anéis', 'Alianças', 'Colares', 'Relógios', 'Consertos', 'Gravação'],
    seoTitle: 'Joalherias - Joias e Relógios',
    seoDescription: 'Encontre joalherias na sua cidade. Anéis, alianças, colares, relógios e consertos. Peças exclusivas e de qualidade.',
    seoKeywords: ['joalheria', 'joias', 'aliança', 'anel de noivado', 'relógio', 'ouro', 'prata'],
    heroTitle: 'Encontre as Melhores Joalherias',
    heroSubtitle: 'Joias e relógios para momentos especiais. Qualidade e elegância!',
    longDescription: 'Encontre joalherias de confiança na sua região. Alianças, anéis de noivado, colares, relógios e serviços de conserto.',
    faqs: [
      { question: 'Quanto custa uma aliança?', answer: 'Alianças variam de R$ 200 a R$ 5.000+ dependendo do material e modelo.' },
      { question: 'Joalheria faz conserto?', answer: 'A maioria das joalherias oferece serviço de conserto e restauração de joias.' },
      { question: 'Tem certificado de autenticidade?', answer: 'Joias de qualidade vêm com certificado de autenticidade e garantia.' },
    ],
  },
  {
    name: 'Sapataria',
    slug: 'sapataria',
    icon: 'IconShoe',
    description: 'Calçados e acessórios',
    suggestedServices: ['Sapatos Femininos', 'Sapatos Masculinos', 'Tênis', 'Bolsas', 'Consertos', 'Palmilhas'],
    seoTitle: 'Sapatarias - Calçados e Bolsas',
    seoDescription: 'Encontre sapatarias na sua cidade. Sapatos, tênis, bolsas e consertos. Conforto e estilo para seus pés!',
    seoKeywords: ['sapataria', 'sapatos', 'calçados', 'tênis', 'bolsas', 'conserto de sapato'],
    heroTitle: 'Encontre as Melhores Sapatarias',
    heroSubtitle: 'Calçados confortáveis e estilosos. Encontre o par perfeito!',
    longDescription: 'Encontre sapatarias de qualidade na sua região. Sapatos, tênis, sandálias, bolsas e serviços de conserto.',
    faqs: [
      { question: 'Sapataria faz conserto?', answer: 'Muitas sapatarias oferecem serviço de conserto, troca de sola e restauração.' },
      { question: 'Tem calçados ortopédicos?', answer: 'Algumas sapatarias são especializadas em calçados ortopédicos e de conforto.' },
      { question: 'Aceita encomenda?', answer: 'Algumas sapatarias trabalham com calçados sob medida ou encomenda.' },
    ],
  },
  {
    name: 'Livraria',
    slug: 'livraria',
    icon: 'IconBook',
    description: 'Livros e papelaria',
    suggestedServices: ['Livros', 'Papelaria', 'Presentes', 'Encomendas', 'E-books', 'Eventos'],
    seoTitle: 'Livrarias - Livros e Papelaria',
    seoDescription: 'Encontre livrarias na sua cidade. Livros, papelaria, presentes e encomendas. Descubra novos mundos!',
    seoKeywords: ['livraria', 'livros', 'papelaria', 'livro infantil', 'best seller', 'literatura'],
    heroTitle: 'Encontre as Melhores Livrarias',
    heroSubtitle: 'Livros para todos os gostos. Descubra sua próxima leitura!',
    longDescription: 'Encontre livrarias na sua região. Livros de todos os gêneros, papelaria, presentes e eventos literários.',
    faqs: [
      { question: 'Livraria faz encomenda?', answer: 'Sim, a maioria das livrarias pode encomendar títulos que não estão em estoque.' },
      { question: 'Tem seção infantil?', answer: 'A maioria das livrarias tem seção dedicada a livros infantis e juvenis.' },
      { question: 'Livraria faz eventos?', answer: 'Algumas livrarias promovem eventos como lançamentos e clubes de leitura.' },
    ],
  },
  {
    name: 'Loja de Bicicletas',
    slug: 'loja-de-bicicletas',
    icon: 'IconBike',
    description: 'Bicicletas e acessórios',
    suggestedServices: ['Bicicletas', 'Peças', 'Acessórios', 'Manutenção', 'Bike Fit', 'Aluguel'],
    seoTitle: 'Lojas de Bicicletas - Bikes e Acessórios',
    seoDescription: 'Encontre lojas de bicicletas na sua cidade. Bikes, peças, acessórios e manutenção. Pedale com qualidade!',
    seoKeywords: ['loja de bicicletas', 'bike', 'bicicleta', 'peças bike', 'acessórios ciclismo', 'manutenção bike'],
    heroTitle: 'Encontre Lojas de Bicicletas',
    heroSubtitle: 'Bicicletas para todos os estilos. Venda, acessórios e manutenção!',
    longDescription: 'Encontre lojas de bicicletas na sua região. Bikes de todos os tipos, peças, acessórios e serviços de manutenção.',
    faqs: [
      { question: 'Loja faz manutenção?', answer: 'A maioria das lojas de bicicletas oferece serviço de manutenção e revisão.' },
      { question: 'Tem bike elétrica?', answer: 'Muitas lojas trabalham com bicicletas elétricas e convencionais.' },
      { question: 'Oferece bike fit?', answer: 'Algumas lojas especializadas oferecem serviço de bike fit para ajuste ergonômico.' },
    ],
  },
  {
    name: 'Conveniência',
    slug: 'conveniencia',
    icon: 'IconBuildingStore',
    description: 'Loja de conveniência 24h',
    suggestedServices: ['Bebidas', 'Snacks', 'Cigarros', 'Produtos Básicos', 'Recargas', 'Gelo'],
    seoTitle: 'Lojas de Conveniência - Aberto 24h',
    seoDescription: 'Encontre lojas de conveniência na sua cidade. Bebidas, snacks e produtos básicos. Muitas funcionam 24h!',
    seoKeywords: ['loja de conveniência', 'conveniência 24h', 'bebidas', 'snacks', 'posto', 'mercadinho'],
    heroTitle: 'Encontre Lojas de Conveniência',
    heroSubtitle: 'Praticidade a qualquer hora. Muitas abertas 24 horas!',
    longDescription: 'Encontre lojas de conveniência na sua região. Bebidas, snacks, produtos básicos e muito mais, muitas abertas 24h.',
    faqs: [
      { question: 'Funciona 24 horas?', answer: 'Muitas lojas de conveniência funcionam 24h, especialmente em postos de gasolina.' },
      { question: 'Tem bebida gelada?', answer: 'Sim, lojas de conveniência geralmente têm bebidas geladas disponíveis.' },
      { question: 'Aceita cartão?', answer: 'A maioria das lojas de conveniência aceita cartões de crédito e débito.' },
    ],
  },
  {
    name: 'Distribuidora de Bebidas',
    slug: 'distribuidora-bebidas',
    icon: 'IconBottle',
    description: 'Bebidas no atacado e varejo',
    suggestedServices: ['Cervejas', 'Refrigerantes', 'Água', 'Destilados', 'Vinhos', 'Gelo'],
    seoTitle: 'Distribuidoras de Bebidas - Atacado e Varejo',
    seoDescription: 'Encontre distribuidoras de bebidas na sua cidade. Cervejas, refrigerantes, destilados e delivery. Preços de atacado!',
    seoKeywords: ['distribuidora de bebidas', 'cerveja', 'bebidas atacado', 'refrigerante', 'delivery bebidas'],
    heroTitle: 'Encontre Distribuidoras de Bebidas',
    heroSubtitle: 'Bebidas geladas com preço de atacado. Delivery disponível!',
    longDescription: 'Encontre distribuidoras de bebidas na sua região. Cervejas, refrigerantes, destilados e vinhos com preços de atacado e delivery.',
    faqs: [
      { question: 'Distribuidora entrega?', answer: 'A maioria das distribuidoras oferece delivery, muitas com taxa grátis acima de determinado valor.' },
      { question: 'Tem preço de atacado?', answer: 'Sim, distribuidoras oferecem preços especiais para compras em quantidade.' },
      { question: 'Entrega bebida gelada?', answer: 'Muitas distribuidoras entregam bebidas já geladas. Consulte disponibilidade.' },
    ],
  },
  {
    name: 'Shopping Center',
    slug: 'shopping-center',
    icon: 'IconBuildingSkyscraper',
    description: 'Centro comercial e entretenimento',
    suggestedServices: ['Lojas', 'Alimentação', 'Cinema', 'Estacionamento', 'Eventos', 'Serviços'],
    seoTitle: 'Shopping Centers - Compras e Lazer',
    seoDescription: 'Encontre shopping centers na sua cidade. Lojas, alimentação, cinema e entretenimento em um só lugar!',
    seoKeywords: ['shopping center', 'shopping', 'centro comercial', 'compras', 'cinema', 'praça de alimentação'],
    heroTitle: 'Encontre Shopping Centers',
    heroSubtitle: 'Compras, lazer e gastronomia em um só lugar!',
    longDescription: 'Encontre shopping centers na sua região. Diversas lojas, praça de alimentação, cinema e opções de entretenimento.',
    faqs: [
      { question: 'Shopping tem estacionamento?', answer: 'Sim, todos os shoppings oferecem estacionamento, geralmente pago por hora.' },
      { question: 'Qual o horário de funcionamento?', answer: 'Horários variam, mas geralmente das 10h às 22h de segunda a sábado.' },
      { question: 'Shopping tem cinema?', answer: 'A maioria dos shoppings possui cinema com múltiplas salas.' },
    ],
  },
  {
    name: 'Loja de Departamentos',
    slug: 'loja-de-departamentos',
    icon: 'IconBuildingWarehouse',
    description: 'Grande variedade de produtos',
    suggestedServices: ['Roupas', 'Eletrônicos', 'Casa', 'Cama Mesa e Banho', 'Brinquedos', 'Utilidades'],
    seoTitle: 'Lojas de Departamentos - Tudo em Um Lugar',
    seoDescription: 'Encontre lojas de departamentos na sua cidade. Roupas, eletrônicos, casa e muito mais. Variedade e preços!',
    seoKeywords: ['loja de departamentos', 'magazine', 'roupas', 'eletrônicos', 'utilidades', 'variedades'],
    heroTitle: 'Encontre Lojas de Departamentos',
    heroSubtitle: 'Tudo o que você precisa em um só lugar. Variedade e economia!',
    longDescription: 'Encontre lojas de departamentos na sua região. Grande variedade de produtos: roupas, eletrônicos, casa, cama mesa e banho.',
    faqs: [
      { question: 'Loja tem cartão próprio?', answer: 'Muitas lojas de departamentos oferecem cartão próprio com condições especiais.' },
      { question: 'Faz entrega?', answer: 'A maioria oferece entrega para produtos maiores como móveis e eletrodomésticos.' },
      { question: 'Tem garantia estendida?', answer: 'Sim, geralmente é oferecida garantia estendida para eletrônicos e eletrodomésticos.' },
    ],
  },
  // ========== NOVAS CATEGORIAS - ALIMENTAÇÃO ==========
  {
    name: 'Cafeteria',
    slug: 'cafeteria',
    icon: 'IconCoffee',
    description: 'Café especial e acompanhamentos',
    suggestedServices: ['Café Especial', 'Cappuccino', 'Bolos', 'Sanduíches', 'Brunch', 'Coworking'],
    seoTitle: 'Cafeterias - Café Especial',
    seoDescription: 'Encontre cafeterias na sua cidade. Café especial, cappuccino, bolos e ambiente aconchegante. Descubra novos sabores!',
    seoKeywords: ['cafeteria', 'café especial', 'cappuccino', 'café gourmet', 'brunch', 'café da manhã'],
    heroTitle: 'Encontre as Melhores Cafeterias',
    heroSubtitle: 'Café especial e ambiente aconchegante. Descubra seu novo lugar favorito!',
    longDescription: 'Encontre cafeterias de qualidade na sua região. Café especial, cappuccino, bolos artesanais e ambientes perfeitos para trabalhar ou relaxar.',
    faqs: [
      { question: 'Cafeteria tem wifi?', answer: 'A maioria das cafeterias oferece wifi gratuito para clientes.' },
      { question: 'Tem opções veganas?', answer: 'Muitas cafeterias oferecem opções veganas e sem lactose.' },
      { question: 'Posso trabalhar na cafeteria?', answer: 'Sim, muitas cafeterias são preparadas para receber quem quer trabalhar remotamente.' },
    ],
  },
  {
    name: 'Bar',
    slug: 'bar',
    icon: 'IconGlass',
    description: 'Bebidas e entretenimento',
    suggestedServices: ['Drinks', 'Cervejas Artesanais', 'Petiscos', 'Happy Hour', 'Música ao Vivo', 'Eventos'],
    seoTitle: 'Bares - Drinks e Entretenimento',
    seoDescription: 'Encontre os melhores bares da sua cidade. Drinks, cervejas artesanais, petiscos e música ao vivo. Diversão garantida!',
    seoKeywords: ['bar', 'drinks', 'cerveja artesanal', 'happy hour', 'boteco', 'pub', 'música ao vivo'],
    heroTitle: 'Encontre os Melhores Bares',
    heroSubtitle: 'Drinks, petiscos e boa música. Encontre seu bar favorito!',
    longDescription: 'Encontre bares de qualidade na sua região. Drinks especiais, cervejas artesanais, petiscos e ambiente descontraído.',
    faqs: [
      { question: 'Bar tem happy hour?', answer: 'Muitos bares oferecem happy hour com descontos em bebidas e petiscos.' },
      { question: 'Tem música ao vivo?', answer: 'Alguns bares oferecem música ao vivo em dias específicos. Verifique a programação.' },
      { question: 'Precisa reservar?', answer: 'Para grupos grandes ou em dias movimentados, recomenda-se reservar.' },
    ],
  },
  {
    name: 'Casa Noturna',
    slug: 'casa-noturna',
    icon: 'IconMoon',
    description: 'Baladas e eventos noturnos',
    suggestedServices: ['Balada', 'Shows', 'Drinks', 'Área VIP', 'Eventos', 'Festas Temáticas'],
    seoTitle: 'Casas Noturnas - Baladas e Shows',
    seoDescription: 'Encontre casas noturnas na sua cidade. Baladas, shows, DJs e eventos especiais. Sua noite começa aqui!',
    seoKeywords: ['casa noturna', 'balada', 'club', 'boate', 'festa', 'DJ', 'vida noturna'],
    heroTitle: 'Encontre Casas Noturnas',
    heroSubtitle: 'Baladas, shows e festas. Sua noite começa aqui!',
    longDescription: 'Encontre casas noturnas na sua região. Baladas, shows com DJs renomados, áreas VIP e eventos temáticos.',
    faqs: [
      { question: 'Quanto custa a entrada?', answer: 'Valores variam conforme o dia e evento. Mulheres geralmente têm entrada gratuita ou desconto.' },
      { question: 'Tem área VIP?', answer: 'A maioria das casas noturnas oferece área VIP com reserva de mesa e garrafa.' },
      { question: 'Qual o dress code?', answer: 'Cada casa tem suas regras. Geralmente é proibido chinelo e bermuda masculina.' },
    ],
  },
  {
    name: 'Delivery',
    slug: 'delivery',
    icon: 'IconMoped',
    description: 'Entrega de comida e produtos',
    suggestedServices: ['Comida', 'Bebidas', 'Mercado', 'Farmácia', 'Pet', 'Conveniência'],
    seoTitle: 'Delivery - Entrega Rápida',
    seoDescription: 'Encontre serviços de delivery na sua cidade. Comida, bebidas, mercado e muito mais entregue na sua porta!',
    seoKeywords: ['delivery', 'entrega', 'comida delivery', 'pedido online', 'entrega rápida'],
    heroTitle: 'Encontre Serviços de Delivery',
    heroSubtitle: 'Tudo entregue na sua porta. Comida, bebidas e muito mais!',
    longDescription: 'Encontre serviços de delivery na sua região. Restaurantes, mercados, farmácias e conveniências com entrega rápida.',
    faqs: [
      { question: 'Quanto tempo demora a entrega?', answer: 'O tempo varia conforme distância e estabelecimento, geralmente 30-60 minutos.' },
      { question: 'Tem taxa de entrega?', answer: 'A maioria dos estabelecimentos cobra taxa de entrega baseada na distância.' },
      { question: 'Posso agendar entrega?', answer: 'Alguns serviços permitem agendar a entrega para um horário específico.' },
    ],
  },
  // ========== NOVAS CATEGORIAS - SAÚDE E BEM-ESTAR ==========
  {
    name: 'Spa',
    slug: 'spa',
    icon: 'IconMassage',
    description: 'Relaxamento e bem-estar',
    suggestedServices: ['Massagem', 'Day Spa', 'Sauna', 'Tratamentos Faciais', 'Hidromassagem', 'Relaxamento'],
    seoTitle: 'Spas - Relaxamento e Bem-estar',
    seoDescription: 'Encontre spas na sua cidade. Massagens, day spa, sauna e tratamentos relaxantes. Cuide de você!',
    seoKeywords: ['spa', 'massagem', 'day spa', 'relaxamento', 'bem-estar', 'sauna', 'tratamento facial'],
    heroTitle: 'Encontre os Melhores Spas',
    heroSubtitle: 'Relaxamento e bem-estar para corpo e mente. Agende seu day spa!',
    longDescription: 'Encontre spas de qualidade na sua região. Massagens relaxantes, day spa, sauna e tratamentos para renovar suas energias.',
    faqs: [
      { question: 'Quanto custa um day spa?', answer: 'Pacotes de day spa variam de R$ 200 a R$ 800, dependendo dos tratamentos incluídos.' },
      { question: 'Precisa agendar?', answer: 'Sim, é importante agendar com antecedência, especialmente para fins de semana.' },
      { question: 'Spa atende casais?', answer: 'Muitos spas oferecem pacotes especiais para casais com sala privativa.' },
    ],
  },
  {
    name: 'Fisioterapeuta',
    slug: 'fisioterapeuta',
    icon: 'IconStretching',
    description: 'Fisioterapia e reabilitação',
    suggestedServices: ['Fisioterapia', 'RPG', 'Pilates', 'Acupuntura', 'Quiropraxia', 'Reabilitação'],
    seoTitle: 'Fisioterapeutas - Reabilitação e Bem-estar',
    seoDescription: 'Encontre fisioterapeutas na sua cidade. Fisioterapia, RPG, pilates e reabilitação. Recupere sua qualidade de vida!',
    seoKeywords: ['fisioterapeuta', 'fisioterapia', 'RPG', 'pilates', 'reabilitação', 'dor nas costas'],
    heroTitle: 'Encontre Fisioterapeutas',
    heroSubtitle: 'Reabilitação e qualidade de vida com profissionais qualificados.',
    longDescription: 'Encontre fisioterapeutas de confiança na sua região. Fisioterapia ortopédica, neurológica, RPG, pilates e muito mais.',
    faqs: [
      { question: 'Quanto custa sessão de fisioterapia?', answer: 'Sessões variam de R$ 80 a R$ 250, dependendo da especialidade e região.' },
      { question: 'Fisioterapeuta atende convênio?', answer: 'Muitos fisioterapeutas aceitam convênios. Verifique no perfil do profissional.' },
      { question: 'Quantas sessões preciso?', answer: 'O número de sessões varia conforme o caso, geralmente definido na avaliação inicial.' },
    ],
  },
  {
    name: 'Médico',
    slug: 'medico',
    icon: 'IconUserMd',
    description: 'Consultórios médicos',
    suggestedServices: ['Clínico Geral', 'Cardiologia', 'Dermatologia', 'Ginecologia', 'Pediatria', 'Ortopedia'],
    seoTitle: 'Médicos - Especialistas de Confiança',
    seoDescription: 'Encontre médicos na sua cidade. Clínico geral, especialistas e exames. Cuide da sua saúde com profissionais qualificados!',
    seoKeywords: ['médico', 'clínico geral', 'especialista', 'consulta médica', 'cardiologista', 'dermatologista'],
    heroTitle: 'Encontre Médicos Especialistas',
    heroSubtitle: 'Profissionais qualificados para cuidar da sua saúde.',
    longDescription: 'Encontre médicos de diversas especialidades na sua região. Clínico geral, cardiologia, dermatologia, ginecologia e muito mais.',
    faqs: [
      { question: 'Quanto custa consulta médica?', answer: 'Consultas particulares variam de R$ 150 a R$ 500, dependendo da especialidade.' },
      { question: 'Médico atende convênio?', answer: 'Muitos médicos aceitam diversos convênios. Verifique no perfil do profissional.' },
      { question: 'Como agendar consulta?', answer: 'Entre em contato via WhatsApp ou telefone para verificar disponibilidade.' },
    ],
  },
  {
    name: 'Hospital',
    slug: 'hospital',
    icon: 'IconBuildingHospital',
    description: 'Atendimento hospitalar',
    suggestedServices: ['Emergência', 'Internação', 'Cirurgias', 'UTI', 'Maternidade', 'Exames'],
    seoTitle: 'Hospitais - Atendimento de Emergência',
    seoDescription: 'Encontre hospitais na sua cidade. Emergência 24h, internação, cirurgias e maternidade. Saúde com qualidade!',
    seoKeywords: ['hospital', 'emergência', 'pronto socorro', 'internação', 'cirurgia', 'maternidade'],
    heroTitle: 'Encontre Hospitais',
    heroSubtitle: 'Atendimento de emergência e cuidados hospitalares de qualidade.',
    longDescription: 'Encontre hospitais na sua região. Atendimento de emergência 24h, internação, cirurgias, maternidade e exames.',
    faqs: [
      { question: 'Hospital atende emergência 24h?', answer: 'A maioria dos hospitais possui pronto socorro 24h. Verifique no perfil.' },
      { question: 'Hospital aceita convênio?', answer: 'Muitos hospitais aceitam diversos convênios. Consulte antes do atendimento.' },
      { question: 'Como funciona internação?', answer: 'A internação pode ser eletiva (agendada) ou de emergência, conforme necessidade médica.' },
    ],
  },
  // ========== NOVAS CATEGORIAS - SERVIÇOS ==========
  {
    name: 'Seguradora',
    slug: 'seguradora',
    icon: 'IconShieldCheck',
    description: 'Seguros e proteção',
    suggestedServices: ['Seguro Auto', 'Seguro Residencial', 'Seguro de Vida', 'Seguro Saúde', 'Previdência', 'Consórcios'],
    seoTitle: 'Seguradoras - Proteção e Segurança',
    seoDescription: 'Encontre seguradoras na sua cidade. Seguro auto, residencial, vida e saúde. Proteja o que é importante!',
    seoKeywords: ['seguradora', 'seguro auto', 'seguro residencial', 'seguro de vida', 'corretor de seguros'],
    heroTitle: 'Encontre Seguradoras',
    heroSubtitle: 'Proteção para você, sua família e seu patrimônio.',
    longDescription: 'Encontre seguradoras e corretores de seguros na sua região. Seguro auto, residencial, vida, saúde e muito mais.',
    faqs: [
      { question: 'Quanto custa seguro auto?', answer: 'O valor varia conforme veículo, perfil e cobertura. Solicite cotação personalizada.' },
      { question: 'Seguro cobre enchente?', answer: 'Depende da cobertura contratada. Verifique as condições da apólice.' },
      { question: 'Como acionar o seguro?', answer: 'Em caso de sinistro, entre em contato com a central 24h da seguradora.' },
    ],
  },
  {
    name: 'Agência de Viagens',
    slug: 'agencia-de-viagens',
    icon: 'IconPlane',
    description: 'Turismo e viagens',
    suggestedServices: ['Passagens', 'Pacotes', 'Hotéis', 'Cruzeiros', 'Intercâmbio', 'Seguro Viagem'],
    seoTitle: 'Agências de Viagens - Turismo',
    seoDescription: 'Encontre agências de viagens na sua cidade. Passagens, pacotes, hotéis e cruzeiros. Realize o sonho da sua viagem!',
    seoKeywords: ['agência de viagens', 'viagem', 'pacote turístico', 'passagem aérea', 'cruzeiro', 'hotel'],
    heroTitle: 'Encontre Agências de Viagens',
    heroSubtitle: 'Realize o sonho da sua viagem. Passagens, pacotes e muito mais!',
    longDescription: 'Encontre agências de viagens na sua região. Passagens aéreas, pacotes turísticos, hotéis, cruzeiros e intercâmbio.',
    faqs: [
      { question: 'Agência parcelar viagem?', answer: 'Sim, a maioria das agências oferece parcelamento em até 12x no cartão.' },
      { question: 'Precisa de visto?', answer: 'Depende do destino. A agência orienta sobre documentação necessária.' },
      { question: 'Pacote inclui seguro viagem?', answer: 'Alguns pacotes incluem, outros oferecem como adicional. Sempre recomendado!' },
    ],
  },
  {
    name: 'Banco',
    slug: 'banco',
    icon: 'IconBuildingBank',
    description: 'Serviços bancários',
    suggestedServices: ['Conta Corrente', 'Empréstimo', 'Financiamento', 'Investimentos', 'Cartões', 'Seguros'],
    seoTitle: 'Bancos - Serviços Financeiros',
    seoDescription: 'Encontre agências bancárias na sua cidade. Conta corrente, empréstimos, financiamentos e investimentos.',
    seoKeywords: ['banco', 'agência bancária', 'empréstimo', 'financiamento', 'conta corrente', 'investimento'],
    heroTitle: 'Encontre Agências Bancárias',
    heroSubtitle: 'Serviços financeiros para suas necessidades.',
    longDescription: 'Encontre agências bancárias na sua região. Abertura de conta, empréstimos, financiamentos, investimentos e muito mais.',
    faqs: [
      { question: 'Como abrir conta?', answer: 'Leve RG, CPF, comprovante de residência e renda para abrir sua conta.' },
      { question: 'Banco faz empréstimo?', answer: 'Sim, os bancos oferecem diversas linhas de crédito. Consulte taxas e condições.' },
      { question: 'Tem atendimento prioritário?', answer: 'Sim, idosos, gestantes e pessoas com deficiência têm atendimento prioritário.' },
    ],
  },
  {
    name: 'Lavanderia',
    slug: 'lavanderia',
    icon: 'IconWashMachine',
    description: 'Lavagem de roupas',
    suggestedServices: ['Lavagem', 'Secagem', 'Passadoria', 'Lavagem a Seco', 'Delivery', 'Tingimento'],
    seoTitle: 'Lavanderias - Lavagem de Roupas',
    seoDescription: 'Encontre lavanderias na sua cidade. Lavagem, secagem, passadoria e lavagem a seco. Roupas limpas sem trabalho!',
    seoKeywords: ['lavanderia', 'lavagem de roupa', 'lavagem a seco', 'passadoria', 'delivery lavanderia'],
    heroTitle: 'Encontre Lavanderias',
    heroSubtitle: 'Roupas limpas e passadas sem trabalho. Delivery disponível!',
    longDescription: 'Encontre lavanderias de qualidade na sua região. Lavagem, secagem, passadoria, lavagem a seco e delivery.',
    faqs: [
      { question: 'Quanto custa lavar roupa?', answer: 'Preços variam: lavagem por kg (R$ 15-30) ou por peça. Lavagem a seco é mais cara.' },
      { question: 'Lavanderia entrega?', answer: 'Muitas lavanderias oferecem serviço de coleta e entrega em domicílio.' },
      { question: 'Quanto tempo demora?', answer: 'Lavagem comum: 24-48h. Lavagem a seco: 2-5 dias dependendo da peça.' },
    ],
  },
  {
    name: 'Chaveiro',
    slug: 'chaveiro',
    icon: 'IconKey',
    description: 'Cópias de chaves e fechaduras',
    suggestedServices: ['Cópias de Chaves', 'Abertura de Portas', 'Fechaduras', 'Cofres', 'Chaveiro Auto', 'Emergência 24h'],
    seoTitle: 'Chaveiros - Chaves e Fechaduras',
    seoDescription: 'Encontre chaveiros na sua cidade. Cópias de chaves, abertura de portas, fechaduras e atendimento 24h.',
    seoKeywords: ['chaveiro', 'cópia de chave', 'abertura de porta', 'fechadura', 'chaveiro 24h', 'chave codificada'],
    heroTitle: 'Encontre Chaveiros',
    heroSubtitle: 'Chaves, fechaduras e abertura de portas. Atendimento 24h!',
    longDescription: 'Encontre chaveiros de confiança na sua região. Cópias de chaves, abertura de portas, troca de fechaduras e atendimento emergencial.',
    faqs: [
      { question: 'Chaveiro atende 24h?', answer: 'Muitos chaveiros oferecem atendimento emergencial 24h. Verifique disponibilidade.' },
      { question: 'Quanto custa cópia de chave?', answer: 'Chaves simples: R$ 5-15. Chaves codificadas: R$ 50-300 dependendo do modelo.' },
      { question: 'Chaveiro faz chave de carro?', answer: 'Sim, chaveiros especializados fazem chaves codificadas e controles de carro.' },
    ],
  },
  {
    name: 'Eletricista',
    slug: 'eletricista',
    icon: 'IconBolt',
    description: 'Serviços elétricos',
    suggestedServices: ['Instalação Elétrica', 'Manutenção', 'Reparos', 'Iluminação', 'Quadro de Luz', 'Emergência'],
    seoTitle: 'Eletricistas - Serviços Elétricos',
    seoDescription: 'Encontre eletricistas na sua cidade. Instalação, manutenção, reparos e emergência. Profissionais qualificados!',
    seoKeywords: ['eletricista', 'instalação elétrica', 'reparo elétrico', 'iluminação', 'quadro de luz'],
    heroTitle: 'Encontre Eletricistas',
    heroSubtitle: 'Serviços elétricos com segurança e qualidade.',
    longDescription: 'Encontre eletricistas qualificados na sua região. Instalações, manutenções, reparos e atendimento emergencial.',
    faqs: [
      { question: 'Quanto cobra um eletricista?', answer: 'O valor varia conforme o serviço. Visitas técnicas custam de R$ 80 a R$ 150.' },
      { question: 'Eletricista emite ART?', answer: 'Eletricistas qualificados emitem ART (Anotação de Responsabilidade Técnica) quando necessário.' },
      { question: 'Atende emergência?', answer: 'Muitos eletricistas oferecem atendimento emergencial com taxa adicional.' },
    ],
  },
  {
    name: 'Encanador',
    slug: 'encanador',
    icon: 'IconDroplet',
    description: 'Serviços hidráulicos',
    suggestedServices: ['Desentupimento', 'Vazamentos', 'Instalações', 'Caixa D\'água', 'Aquecedor', 'Emergência'],
    seoTitle: 'Encanadores - Serviços Hidráulicos',
    seoDescription: 'Encontre encanadores na sua cidade. Desentupimento, vazamentos, instalações e emergência. Resolva seu problema!',
    seoKeywords: ['encanador', 'desentupimento', 'vazamento', 'hidráulica', 'caixa d\'água', 'encanador 24h'],
    heroTitle: 'Encontre Encanadores',
    heroSubtitle: 'Serviços hidráulicos com rapidez e qualidade.',
    longDescription: 'Encontre encanadores de confiança na sua região. Desentupimento, reparos de vazamentos, instalações e atendimento emergencial.',
    faqs: [
      { question: 'Quanto custa desentupir?', answer: 'Desentupimento varia de R$ 100 a R$ 500 dependendo do tipo e gravidade.' },
      { question: 'Encanador atende emergência?', answer: 'Muitos encanadores oferecem atendimento 24h para emergências.' },
      { question: 'Quanto custa trocar torneira?', answer: 'O serviço de troca de torneira simples custa em média R$ 50 a R$ 100 + material.' },
    ],
  },
  {
    name: 'Pintor',
    slug: 'pintor',
    icon: 'IconPaint',
    description: 'Pintura residencial e comercial',
    suggestedServices: ['Pintura Interna', 'Pintura Externa', 'Textura', 'Grafiato', 'Impermeabilização', 'Efeitos'],
    seoTitle: 'Pintores - Pintura Residencial e Comercial',
    seoDescription: 'Encontre pintores na sua cidade. Pintura interna, externa, textura e efeitos especiais. Transforme seu ambiente!',
    seoKeywords: ['pintor', 'pintura residencial', 'pintura comercial', 'textura', 'grafiato', 'pintor de parede'],
    heroTitle: 'Encontre Pintores',
    heroSubtitle: 'Pintura profissional para transformar seu ambiente.',
    longDescription: 'Encontre pintores qualificados na sua região. Pintura interna, externa, textura, grafiato e efeitos especiais.',
    faqs: [
      { question: 'Quanto custa pintar um cômodo?', answer: 'O valor varia de R$ 20 a R$ 40 por m², dependendo do tipo de pintura.' },
      { question: 'Pintor fornece material?', answer: 'Alguns pintores incluem material no orçamento, outros cobram apenas mão de obra.' },
      { question: 'Quanto tempo demora?', answer: 'Um cômodo leva de 1 a 3 dias. Casa completa pode levar 1 a 2 semanas.' },
    ],
  },
  {
    name: 'Empresa de Mudanças',
    slug: 'empresa-de-mudancas',
    icon: 'IconTruck',
    description: 'Mudanças residenciais e comerciais',
    suggestedServices: ['Mudança Residencial', 'Mudança Comercial', 'Embalagem', 'Montagem', 'Guarda-Móveis', 'Içamento'],
    seoTitle: 'Empresas de Mudanças - Transporte Seguro',
    seoDescription: 'Encontre empresas de mudanças na sua cidade. Mudança residencial, comercial, embalagem e montagem. Transporte seguro!',
    seoKeywords: ['empresa de mudança', 'mudança residencial', 'mudança comercial', 'frete', 'carreto', 'transporte móveis'],
    heroTitle: 'Encontre Empresas de Mudanças',
    heroSubtitle: 'Mudança segura e tranquila. Residencial ou comercial.',
    longDescription: 'Encontre empresas de mudanças de confiança na sua região. Mudanças residenciais, comerciais, embalagem, montagem e guarda-móveis.',
    faqs: [
      { question: 'Quanto custa uma mudança?', answer: 'O valor depende da quantidade, distância e serviços. Solicite orçamento detalhado.' },
      { question: 'Mudança tem seguro?', answer: 'Empresas sérias oferecem seguro para os itens transportados. Sempre verifique.' },
      { question: 'Empresa faz embalagem?', answer: 'Muitas empresas oferecem serviço completo incluindo embalagem de todos os itens.' },
    ],
  },
  {
    name: 'Locadora de Veículos',
    slug: 'locadora-de-veiculos',
    icon: 'IconCarRental',
    description: 'Aluguel de carros e motos',
    suggestedServices: ['Carros', 'Motos', 'Vans', 'Caminhões', 'Diária', 'Mensal'],
    seoTitle: 'Locadoras de Veículos - Aluguel de Carros',
    seoDescription: 'Encontre locadoras de veículos na sua cidade. Aluguel de carros, motos e vans. Diária ou mensal com os melhores preços!',
    seoKeywords: ['locadora de veículos', 'aluguel de carro', 'rent a car', 'locação de veículos', 'aluguel de moto'],
    heroTitle: 'Encontre Locadoras de Veículos',
    heroSubtitle: 'Alugue carros, motos e vans com facilidade.',
    longDescription: 'Encontre locadoras de veículos na sua região. Aluguel de carros, motos, vans e caminhões por diária, semanal ou mensal.',
    faqs: [
      { question: 'Precisa de cartão de crédito?', answer: 'A maioria das locadoras exige cartão de crédito para caução. Algumas aceitam débito.' },
      { question: 'Qual idade mínima?', answer: 'Geralmente 21 anos com CNH há pelo menos 2 anos.' },
      { question: 'Posso devolver em outra cidade?', answer: 'Muitas locadoras permitem devolução em outra cidade com taxa adicional.' },
    ],
  },
  // ========== NOVAS CATEGORIAS - ENTRETENIMENTO E OUTROS ==========
  {
    name: 'Cinema',
    slug: 'cinema',
    icon: 'IconMovie',
    description: 'Filmes e entretenimento',
    suggestedServices: ['Filmes 2D', 'Filmes 3D', 'IMAX', 'Bomboniere', 'Sala VIP', 'Eventos'],
    seoTitle: 'Cinemas - Filmes e Entretenimento',
    seoDescription: 'Encontre cinemas na sua cidade. Filmes em cartaz, salas 3D, IMAX e muito mais. Confira a programação!',
    seoKeywords: ['cinema', 'filme', 'filme em cartaz', 'cinema 3D', 'IMAX', 'sessão de cinema'],
    heroTitle: 'Encontre Cinemas',
    heroSubtitle: 'Os melhores filmes em cartaz. Confira a programação!',
    longDescription: 'Encontre cinemas na sua região. Veja filmes em cartaz, horários das sessões, salas 3D, IMAX e promoções.',
    faqs: [
      { question: 'Quanto custa ingresso?', answer: 'Ingressos variam de R$ 20 a R$ 60 dependendo do dia, horário e tipo de sala.' },
      { question: 'Tem meia-entrada?', answer: 'Sim, estudantes, idosos e outros grupos têm direito a meia-entrada.' },
      { question: 'Posso comprar online?', answer: 'A maioria dos cinemas permite compra de ingresso online ou pelo aplicativo.' },
    ],
  },
  {
    name: 'Museu',
    slug: 'museu',
    icon: 'IconBuildingCastle',
    description: 'Arte, história e cultura',
    suggestedServices: ['Exposições', 'Visitas Guiadas', 'Eventos', 'Loja', 'Café', 'Educativo'],
    seoTitle: 'Museus - Arte, História e Cultura',
    seoDescription: 'Encontre museus na sua cidade. Exposições, visitas guiadas e programação cultural. Descubra arte e história!',
    seoKeywords: ['museu', 'exposição', 'arte', 'história', 'cultura', 'visita guiada', 'galeria'],
    heroTitle: 'Encontre Museus',
    heroSubtitle: 'Arte, história e cultura. Descubra exposições incríveis!',
    longDescription: 'Encontre museus na sua região. Exposições de arte, história, ciência e muito mais. Visitas guiadas e programação especial.',
    faqs: [
      { question: 'Museu é pago?', answer: 'Varia conforme o museu. Muitos têm entrada gratuita ou dia de acesso livre.' },
      { question: 'Tem visita guiada?', answer: 'A maioria dos museus oferece visitas guiadas gratuitas ou pagas.' },
      { question: 'Posso fotografar?', answer: 'Depende do museu e da exposição. Verifique as regras antes da visita.' },
    ],
  },
  {
    name: 'Posto de Combustível',
    slug: 'posto-de-combustivel',
    icon: 'IconGasStation',
    description: 'Combustíveis e conveniência',
    suggestedServices: ['Gasolina', 'Etanol', 'Diesel', 'GNV', 'Conveniência', 'Lavagem'],
    seoTitle: 'Postos de Combustível - Abastecimento',
    seoDescription: 'Encontre postos de combustível na sua cidade. Gasolina, etanol, diesel e GNV. Compare preços e serviços!',
    seoKeywords: ['posto de gasolina', 'combustível', 'gasolina', 'etanol', 'diesel', 'GNV', 'posto 24h'],
    heroTitle: 'Encontre Postos de Combustível',
    heroSubtitle: 'Abastecimento de qualidade. Compare preços na sua região!',
    longDescription: 'Encontre postos de combustível na sua região. Gasolina, etanol, diesel, GNV, conveniência e outros serviços.',
    faqs: [
      { question: 'Posto funciona 24h?', answer: 'Muitos postos funcionam 24h. Verifique no perfil do estabelecimento.' },
      { question: 'Tem conveniência?', answer: 'A maioria dos postos possui loja de conveniência com diversos produtos.' },
      { question: 'Aceita vale combustível?', answer: 'Muitos postos aceitam vales combustível de diversas empresas.' },
    ],
  },
  {
    name: 'Outro',
    slug: 'outro',
    icon: 'IconBuildingStore',
    description: 'Outros tipos de negócio',
    suggestedServices: ['Atendimento Especializado', 'Orçamento Gratuito', 'Atendimento Rápido', 'Garantia de Satisfação'],
    seoTitle: 'Negócios Locais - Encontre Tudo',
    seoDescription: 'Encontre diversos tipos de negócios locais na sua cidade. Serviços especializados com avaliações reais.',
    seoKeywords: ['negócio local', 'serviços', 'empresa', 'profissional', 'prestador de serviço'],
    heroTitle: 'Encontre Negócios Locais',
    heroSubtitle: 'Diversos tipos de negócios e serviços na sua região.',
    longDescription: 'Encontre diversos tipos de negócios locais. Compare avaliações e escolha o melhor para suas necessidades.',
    faqs: [
      { question: 'Como encontrar o serviço ideal?', answer: 'Use os filtros de busca e compare avaliações de outros clientes.' },
      { question: 'Como entrar em contato?', answer: 'Você pode entrar em contato via WhatsApp ou telefone, disponíveis no perfil.' },
      { question: 'Os negócios são verificados?', answer: 'Sim, todos os negócios são verificados e as avaliações são de clientes reais.' },
    ],
  },
]

async function seed() {
  console.log('🌱 Iniciando seed de categorias...')

  for (const cat of CATEGORIES_SEED) {
    await db
      .insert(category)
      .values(cat)
      .onConflictDoUpdate({
        target: category.slug,
        set: {
          name: cat.name,
          icon: cat.icon,
          description: cat.description,
          suggestedServices: cat.suggestedServices,
          seoTitle: cat.seoTitle,
          seoDescription: cat.seoDescription,
          seoKeywords: cat.seoKeywords,
          heroTitle: cat.heroTitle,
          heroSubtitle: cat.heroSubtitle,
          longDescription: cat.longDescription,
          faqs: cat.faqs,
        },
      })
    console.log(`✅ Categoria "${cat.name}" inserida/atualizada`)
  }

  console.log('🎉 Seed de categorias concluído!')
  process.exit(0)
}

seed().catch((err) => {
  console.error('❌ Erro no seed:', err)
  process.exit(1)
})
