import type { TemplateConfig } from "@/templates/types";

export const STRATEX_CONFIG: TemplateConfig = {
  id: "stratex",
  name: "Stratex",
  description:
    "Design premium para consultoria e negócios. Serif font (Hedvig Letters), accent teal green, hero escuro, comparison grid, pricing cards, form de contato.",
  thumbnail: "/templates/stratex/thumbnail.png",
  bestFor: [
    "consultoria", "consulting", "negocio", "business", "estrategia",
    "gestao", "financeiro", "contabilidade", "advocacia", "escritorio",
    "coaching", "mentoria", "treinamento", "rh", "recrutamento",
    "seguros", "investimentos", "assessoria", "auditoria", "compliance",
    "b2b", "saas", "plataforma", "agencia", "marketing",
  ],
  forceStyle: "elegant",
  forceRadius: "lg",
  recommendedHeadingFont: "playfair-display",
  recommendedBodyFont: "inter",
  defaultSections: [
    { blockType: "header", variant: 1, name: "Flat Serif Nav", description: "Nav com logo green square + serif links + CTA pill com arrow" },
    { blockType: "hero", variant: 1, name: "Dark Hero", description: "Hero escuro bg accent, stars rating, H1 serif, CTAs, hero image" },
    { blockType: "stats", variant: 1, name: "Partners Bar", description: "Logo marquee de parceiros com grayscale + infinite scroll" },
    { blockType: "about", variant: 1, name: "Comparison Grid", description: "2-col: Other Firms (white) vs Our Firm (green) com checklist" },
    { blockType: "services", variant: 2, name: "Service Cards", description: "Slideshow de cards com imagem bg + gradient overlay + text" },
    { blockType: "testimonials", variant: 1, name: "Dark Carousel", description: "Stars rating + carousel de depoimentos em cards escuros" },
    { blockType: "services", variant: 1, name: "Feature Grid", description: "Grid 3x2 de features com icon accent square + titulo + descricao centralizado" },
    { blockType: "pricing", variant: 1, name: "Pricing Tiers", description: "2 cards: Standard (outline) + Premium (filled green)" },
    { blockType: "services", variant: 3, name: "Numbered Steps", description: "3 steps com imagem + numero + titulo + descricao" },
    { blockType: "stats", variant: 2, name: "Impact Stats", description: "Grid 2x2 ou 4-col com numeros grandes + labels" },
    { blockType: "gallery", variant: 1, name: "Team Carousel", description: "Carousel de membros com foto + nome + cargo overlay" },
    { blockType: "faq", variant: 1, name: "Clean Accordion", description: "Accordion simples full-width com chevron" },
    { blockType: "contact", variant: 1, name: "Dark Form", description: "Secao escura (accent bg) com form de contato" },
    { blockType: "footer", variant: 1, name: "4-Col Footer", description: "Brand + 3 link columns + bottom copyright bar" },
  ],
  availableVariants: {
    header: [1],
    hero: [1],
    stats: [1, 2],
    about: [1],
    services: [1, 2, 3],
    testimonials: [1],
    pricing: [1],
    gallery: [1],
    faq: [1],
    contact: [1],
    footer: [1],
    "whatsapp-float": [1],
  },
};
